
texts.instructions.phase_I.de = ['In der folgenden Aufgabe sehen oder hoeren Sie in zufaelliger '...
                                'Abfolge verschiedene Belohnungen: Essen, Musik oder erotische Bilder. '...
                                'Danach bitten wir Sie jeweils anzugeben, wie sehr Sie die '...
                                'praesentierte Belohnung in diesem Moment gern erhalten wuerden, '...
                                'bzw. wie sehr Sie die gezeigte Belohnung moegen. \n'...
                                'Wie sehr Sie die Belohnung erhalten wollen, bzw. moegen, wird mittels verschiedener Skalen '...
                                'abgefragt: Bitte nutzen Sie die horizontale Skala, um anzugeben, wie sehr Sie '...
                                'die Belohnung in diesem Moment erhalten moechten und die vertikale Skala, um anzugeben, '...
                                'wie sehr Sie die dargestellte Belohnung in diesem Moment moegen. '...
                                'Welche Skala jeweils nach einem Bild erscheint, wird zufaellig ausgewaehlt. \n'...
                                'Benutzen Sie den Joystick, um auf dem Slider zu navigieren '...
                                'und bestaetigen Sie Ihre Antworten anschließend mit dem Button A.'];

texts.instructions.phase_II.de = ['In der folgenden Aufgabe sollen Sie sich jeweils zwischen '...
                                'zwei moeglichen Belohnungen entscheiden. Dazu sehen oder hoeren '...
                                'Sie jeweils zwei verschiedene Belohnungen, '...
                                'die Sie vorher bewertet haben. Danach bitten wir Sie anzugeben, '...
                                'welche Belohnung Sie lieber erhalten moechten.\n'...
                                '\n Um die linke Belohnung zu waehlen, nutzen Sie Button X \n'...
                                'Um die rechte Belohnung zu waehlen, nutzen Sie Button B \n'];
                                
texts.instructions.phase_III.de =['\n Bitte entscheiden Sie spontan, welche Belohnung Sie lieber '...
                                'erhalten wollen, ohne lange nachzudenken.\n'...
                                '\n Sie haben ungefähr 4 Sekunden Zeit, um sich zu entscheiden.'...
                                ' Eine Sekunde vor dem Ende der 4 Sekunden, sehen Sie ein rotes '...
                                'Ausrufezeichen, um Sie auf den baldigen Ablauf der '...
                                'Entscheidungszeit hinzuweisen\n'];
                            
texts.instructions.reward.de = ['Waehrend der Entscheidungaufgabe erhalten Sie zu einigen '...
                                'Zeitpunkten zufaellig eine der vorher gewaehlten '...
                                'Belohnungen, die Sie so laenger (30 Sekunden) '...
                                'geniessen koennen. Ist die Belohnung ein Bild '... 
                                'oder eine Melodie, wird Ihnen dieses 30 Sekunden '...
                                'angezeigt bzw. vorgespielt, ist die Belohnung ein Snack,'...
                                'bekommen Sie diesen angereicht und duerfen ihn innerhalb'...
                                'von 30 Sekunden essen' ];
                            
texts.instructions.reward_II.de = ['Waehrend Sie die Belohnung konsumieren, '...
                                'bitten wir Sie, kontinuierlich zu bewerten, wie sehr sie die '...
                                'Belohnung moegen. Dazu sehen Sie die vertikale Skala, um anzugeben, '...
                                'wie sehr Sie die dargestellte Belohnung in jedem Moment moegen.\n'...
                                '\nBenutzen Sie den Joystick, um auf dem Slider zu navigieren '...
                                'und passen Sie die Bewertung über die gesamte Zeit (30 Sekunden)'...
                                ' an Ihr Empfinden an.\n'...
                                '\nSie müssen die Einschaetzung nicht bestaetigen. \n'];
                            
texts.instructions.reward_III.de = ['Sie erhalten nun eine vorher gewaehlte '...
                                'Belohnung, um sie laenger zu geniessen. '...
                                'Waehrend Sie die Belohnung konsumieren, '...
                                'bitten wir Sie, kontinuierlich zu bewerten, wie sehr sie die '...
                                'Belohnung moegen. Dazu sehen Sie die vertikale Skala, um anzugeben, '...
                                'wie sehr Sie die dargestellte Belohnung in jedem Moment moegen.\n'...
                                '\nBenutzen Sie den Joystick, um auf dem Slider zu navigieren '...
                                'und passen Sie die Bewertung über die gesamte Zeit (30 Sekunden) '...
                                'an Ihr Empfinden an.\n'...
                                '\nSie müssen die Einschaetzung nicht bestaetigen. \n'];


save('texts.mat','texts')