%% Instructions tVNS English

% general

instr.text_coins1     = '1 Money point per second';
instr.text_coins10    = '10 Money points per second';
instr.text_cookies1   = '1 Snack point per second';
instr.text_cookies10  = '10 Snack points per second';

instr.text_Cont       = 'Continue with mouse click.';

% training section
instr.train_welcome_text = ['Welcome.' ...
                            '\n\nThis is a simple game where you will be playing for money and snacks.' ...
                            '\nFor now, you can make yourself comfortable with the functions of the game and practice.' ...
                            ' The actual experiment will start at a later time.'];
                  
instr.train_instr        = ['On the screen, you will see an open container with a blue ball inside.' ...
                            ' When you press the right trigger button on the controller with your index finger, the ball will move up.' ...
                            ' The faster you press the right trigger button, the higher the ball will rise.' ...
                            '\nYou will now have 10 seconds to move the ball as high as possible.' ...
                            '\nThe highest position the ball reaches will be indicated by a blue line.'];
                  
instr.first_round_train  = ['Please do not change how you hold the controller during the game.' ...
                            '\n\nIn the following 10 seconds, try to move the ball as high as you possibly can.'];
                  
instr.last_round_train   = 'Well done! Try to get the ball even higher now.';

% bidding section
           
instr.bidding            = ['The following trials serve to adapt the task specifically to you.' ...
                            '\nIn the following trials, you will see different reward options on the screen' ...
                            ' that you can win in the game. \n\nThe coins represent money,'...
                            ' the chocolate bars represent snacks. Show in the following bidding phase' ...
                            ' how much effort you are willing to exert to win the options shown on the screen.' ...
                            '\nThe duration of each of the trials is about 5 seconds, but this will vary a little.' ...
                            ' Try to keep the ball at the level of effort at which you are willing to "offer."'];  
% experimental phase intro

instr.strt_actual_train  = ['You will now practice the actual task:' ...
                            '\n\nThe line will no longer move with the ball, but instead you should' ...
                            ' try to move the ball up and over the red line by repeatedly pressing the button.' ... 
                            ' You can win points for each full second that the ball is over the red line.' ... 
                            ' You can tell when you are collecting points when the ball changes its color to light blue.'];
                        
instr.intro_exp1         = ['We will now begin with the game that you practiced earlier.' ... 
                            ' As a reminder: This is a simple game where you will be playing for money and snacks.' ...
                            '\n\nTry to move the ball up and over the red line by repeatedly pressing the button.' ... 
                            ' You can win points for each full second that the ball is over the red line.' ... 
                            ' You can tell when you are collecting points when the ball changes its color to light blue.'];

instr.intro_exp2         = ['The difference from the practice session from earlier is that we will also be stimulating the vagus nerve at your ear.' ...
                            ' The experimenter will turn on the stimulation at the start of each trial.'];

                      
% rewards

instr.reward_nr1         = ['You can collect different rewards in each trial.' ...
                            ' You will be playing for both money and calories,'...
                            ' which you can trade in for snacks at the end of the task.'... 
                            ' The reward will be shown with pictures' ... 
                            ' and will remain constant in each of the 30-second trials.'];
                        
instr.reward_nr2         = ['In some trials, you can win money points.'... 
                            ' After the task, you will receive the corresponding amount in euros.'...
                            '\n\nThe following conditions apply:'];
                        
instr.reward_nr3         = ['In some trials, you can win calories.'...
                            ' After the task, you will receive the corresponding number of snacks.'...
                            '\n\nThe following conditions apply:'];

instr.diff_nr1           = ['There will be different levels of difficulty during the experiment.'...
                            ' This will make it not always be possible to keep the ball above the line for the whole trial.'...
                            ' One way to get around this is to take breaks during the trials'...
                            ' so that you can press faster again.'];
                        
instr.diff_exp           =  ['As a reminder: There will be different levels of difficulty during the experiment.'...
                            ' This will make it not always be possible' ...
                            ' to keep the ball above the line for the whole trial. ' ...
                            ' One way to get around this is to take breaks during the trials' ...
                            ' in order to be able to press faster again.']; 
                        
instr.vas_nr1            = ['After each trial, you will be asked two questions:'...
                            '\n\n' char(39) 'How much did you exert yourself in this trial?' char(39) ' \n ' char(39) ...
                            ' How much did you want the reward shown in this trial?' char(39) ...
                            '\n\nYou can respond by pushing a point on a scale from left (not at all) to right (a lot).'...
                            ' The point on the scale can be moved with the left joystick on the controller.'...
                            ' You must then confirm your response by pressing the green A button on the controller.'...
                            '\nPlease be aware that you have a limited amount of time to respond to the questions.'...
                            ' Do not think about the answers for too long, but instead answer spontaneously.'...
                            ' There is no ' char(39) 'right' char(39) ' or ' char(39) 'wrong' char(39) ' answer.'];  
                        
instr.time_train         = ['The following training round will take about 5 minutes.\nIf you have any questions, '...
                            ' you can ask them right now.\nWhen you feel ready, we can begin the experiment.'];
                        
instr.time_exp           = ['The whole experiment will take about 40 minutes.\nIf you have any questions,'...
                            ' you can ask them right now.\nWhen you feel ready, we can begin the experiment.'];
                                
                                
                                