  %%=========================================================================
%
% Smoothes force data (generated by grip force device)
%
% Written by Monja Neuser, Nov 2017,
% adapted by Mechteld, Jan 2019,
% adapted by Wiebke Ringels, September 2020
%
% the workspace contains different struct with different information:
%
% output        raw data (output) from the experiment
% data          processed data that is the output from this file
% files         everything that is needed to save the data to files
% plotting      everything that is needed to plot the data
% smoothing     everything that is needed to smooth force data
% segmentation  everything that is needed to segment the data
%
% Take a look at the README for data processing before working with this 
% script the first time or if questions arises!
%
%%=========================================================================

for runLabel = runLabel_start:2
    
    if runLabel == 1
        smoothing.data = data.MergedTraining;
    else
        smoothing.data = data.MergedExp;
    end
    
    % add smoothed data as new column
    smoothing.data = addvars(smoothing.data, zeros(height(smoothing.data),1), 'NewVariableNames', 'RelEffort_RAW','Before','Diff');

    %% Smoothing of RelEffort
    % for a description of the procedure, take a look at Monja's
    % master thesis!
    
    % start with subject of first row
    smoothing.current_subj = smoothing.data.Subj_ID(1);
    
    % start with trial of first row 
    smoothing.current_trial = smoothing.data.Trial_ID(1);
  
    for i_row = 1:length(smoothing.data.RelEffort)
        
        % track the current state of smoothing
        smoothing.new_subj = smoothing.data.Subj_ID(i_row);
        smoothing.new_trial = smoothing.data.Trial_ID(i_row);
        
        % if a new subject starts, print it to console
        if smoothing.new_subj ~= smoothing.current_subj
            
            smoothing.current_subj = smoothing.new_subj;
            
            % print to console for observation
            if verbose
                if runLabel == 1
                    sprintf(['SMOOTH - TRAINING - Subject: ', num2str(smoothing.current_subj)])
                else
                    sprintf(['SMOOTH - EXP - Subject: ', num2str(smoothing.current_subj)])
                end
            end
        end
        
        % the data is smoothed over one trial, i.e. for each trial the
        % starting values are reset
        % this reset also happens when a new subject/session starts because the
        % trial number then switches from experiment.N to 1!
        if smoothing.new_trial ~= smoothing.current_trial || i_row == 1
            
            smoothing.current_trial = smoothing.new_trial;
            
            % start values
            smoothing.f_prev = 0;
            smoothing.w_prev = 0;
    
            % learning rate lambda
            smoothing.y = 0.6;
        end   
    
        % read out current grip data
        smoothing.f = smoothing.data.RelEffort(i_row);
  
        % compute current weight factor
        smoothing.w = smoothing.y * smoothing.w_prev + 1;
   
        % compute smoothed grip value
        smoothing.f_smooth = (1 - (1 / smoothing.w)) * smoothing.f_prev + (1 / smoothing.w) * smoothing.f;
   
        % update values
        smoothing.f_prev = smoothing.f_smooth;
        smoothing.w_prev = smoothing.w;
    
        % store raw, non-smoothed value
        smoothing.data.RelEffort_RAW(i_row) = smoothing.data.RelEffort(i_row);
        % overwrite RelEffort with smoothed values (if smaller then
        % 0, save 0 as value)
        smoothing.data.RelEffort(i_row) = max(0,smoothing.f_smooth);
    end
    
    if runLabel == 1
        data.MergedTraining = smoothing.data;
    else
        data.MergedExp = smoothing.data;
    end
    
    clearvars smoothing
end

%% end and saving of smoothing process

cd(files.file_dir)
if process_training
    savedata(['EAT_' experiment.paradigm_number '_Train_Merg'], data.MergedTraining, files.data_dir)
    cd(files.file_dir)
end

savedata(['EAT_' experiment.paradigm_number '_Exp_Merg'], data.MergedExp, files.data_dir);

cd(files.effort_dir)