%% Instructions WOF EAT (Seedcorn) German

% general

instr.text_coins1 = '1 money point per second';
instr.text_coins10 = '10 money points per second ';
instr.text_cookies1 = '1 food point per second';
instr.text_cookies10 = '10 food points per second ';

% how to jump through instructions
if settings.do_fmri == 0
     instr.text_Cont = 'Continue with mouse click.';
else
     instr.text_Cont = 'Continue by squeezing.';
end

% training
                   
instr.train_welcome_text = ['Welcome.' ...
                            '\n\nThis is a simple game in which you play for money and a snack.' ...
                            '\nYou can first familiarize yourself with the functions and practice a bit. '...
                            'The actual game will start at a later time.'];
                         
instr.train_instr        = ['On the screen you will immediately see an open container with a blue ball in it. '...
                            'When you squeeze the device in your hand, the ball moves up. '...
                            'The harder you press, the higher the ball rises.' ...
                            '\nIn the next three rounds, you should familiarize yourself with the device.'];

instr.first_round_train  = ['Please do not change your hand position during the experiment. '...
                            '\n\nTry to get the ball as high up as possible in the next 10 seconds. '...
                            '\ nThe highest position reached is shown with a blue line.']; 

instr.first_round_train_mri = ['Welcome. \n\nNext, the game in which you should work with for money and snacks will start again. '...
                               '\nYou can first familiarize yourself with the functions and practice a bit. '...
                               'The actual game will then start at a later time. '...
                               'Please do not move during the measurement and do not change your overall hand position during the game. '...
                               '\n\nFirst, please try to get the ball as high up as you can in the next 10 seconds. '];                         

instr.middle_round_train = 'Hold the device loosely in your hand for the next 10 seconds without squeezing. ';
                  
instr.last_round_train   = 'Try once again to get the ball up as high as possible in the following 10 seconds. ';   


% bidding section
instr.bidding            = ['The following rounds serve to adapt the task individually for you. '...
                           '\nIn several rounds, you will see different options on the screen ' ...
                           'that you can win in this game. \n\ nThe euro coins show monetary amounts, '...
                           'The chocolate bars show snacks. In the subsequent bidding phases, specify '...
                           'How much effort you would be willing to spend to win the options shown.' ...
                           '\nThe duration of a bidding phase is approximately 5 seconds, but varies slightly. '...
                           'Try to keep the ball at the level you intend to ?bid?.'];
% experimental phase

instr.strt_actual_train  = ['Now you will practice the actual task:' ...
                           '\nThe line will no longer move with the ball. '...
                           '\n\nTry pressing to move the ball up and over a red line. '...
                           'You can win points for every full second the ball stays above the red line. '...
                           'You can see that if the ball changes color to light blue you will win something.'];                       

instr.intro_exp1         = ['We will now start with the game that you practiced before. '...
                           'As a reminder, this is a simple game in which you play for money and a snack.' ...
                           '\n\nTry pressing to move the ball up and over a red line. '...
                           'You can win points for every full second the ball stays above the red line. '...
                           'You can see that if the ball changes color to light blue you will win something.'];                       

instr.intro_exp2         = ['The difference to the practice earlier is that in some rounds you will not know exactly where the line is. '...
                           'In the half of the rounds you see a red area instead. '...
                           'The line that the ball has to cross to win points is somewhere inside this area. '...
                           'If you move the ball completely over this area, you will definitely collect food or money points. '...
                           'The ball does not change color in these rounds. '...
                           '\n\n However, as before, after the round you will see how many points you have collected. '...
                           'Then the actual position of the line will also be shown to you.'];                         
                                        
% rewards                   
instr.reward_nr1         = ['You can win different amounts in each round. '...
                           'You will be playing for money as well as for calories,' ...
                           'which you can exchange for a snack after completing the task. '...
                           'What the current reward is remains constant over a 24 second period' ...
                           'and is shown to you with the help of images.'];                        
         
instr.reward_nr2         = ['In some rounds you can win money points. '...
                           'After the task you will receive the corresponding amount of money. '...
                           '\n\nThe following conditions exist:'];                         

instr.reward_nr3         = ['In some runs you can win calories. '...
                           'After completing the task, you will receive the corresponding equivalent as a snack. '...
                           '\n\nThe following conditions exist: '];                         
                                     
% difficulty
                      
instr.diff_nr1           = ['There will be different levels of difficulty in the course of the experiment. '...
                           'So it will not always be possible' ...
                           'to keep the ball completely above the line all the time. '...
                           'One way to deal with this' ...
                           'is to also take breaks during a round' ...
                           'in order to be able to apply more pressure afterwards.'];                        

instr.diff_exp           =  ['Reminder: During the experiment there will be different levels of difficulty. '...
                            'So it will not always be possible' ...
                            'to keep the ball completely above the line all the time. '...
                            'One way to deal with this' ...
                            'is to also take breaks during a round' ...
                            'in order to be able to apply more pressure afterwards.'];                 
% VAS Instructions
                      
instr.vas_nr1          = ['After each round you will be shown a series of three questions:' ...
                          '\n\n How much did you exert yourself in this round? '...
                          '\n How much did you want to receive the reward in this round? '...
                          '\n How happy are you feeling at the moment? '...
                          '\n\n To answer, you can move the controller on a scale (not at all - very). '...
                          'Please use the mouse with your dominant hand. '...
                          'You must then confirm your answer with a click of the mouse. '...
                          '\nPlease note that you only have a limited time for the answers. '...
                          'Do not think too long, but instead respond spontaneously. '...
                          'There is no right or wrong answer.'];                        
                        
                        
% Wheel of fortune related instructions      

instr.wof_train          = ['Next we will practice another game with a wheel of fortune,' ...
                            '\n in which you can win or lose money. '...
                            '\n During the main part of the experiment, the other task,' ...
                            'that you just practiced will sometimes be interrupted by this wheel of fortune game. '...
                            '\n At the end, all winnings and losses from the game will be added together. '...
                            '\n However, the result of this practice round will not count. '];

instr.wof_exp            = ['From time to time the main game will be interrupted by the wheel of fortune game,' ...
                             'in which you can win or lose money. '...
                             '\n All you have to do for this part is click to start it.'];                        
                        
instr.wof_panas          = ['Gleich am Anfang und auch zu vier weiteren Zeitpunkten werden wir Fragen zu ihrem Befinden stellen. '... 
                            '\n Hier haben Sie genau wie bei den Fragen nach jedem Durchgang nur eine begrenzte Zeit zur Verfuegung. '... 
                            '\n Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan. '... 
                            'Es gibt dabei kein Richtig oder Falsch.'];

instr.wof_panas          = ['At the beginning and at four further timepoints we will ask questions about how you feel. '...
                            '\n Just like the questions after each round, you only have a limited amount of time here. '...
                            '\n Do not think too long, but instead respond spontaneously. '...
                            'There is no right or wrong answer.'];
                        
                        
                        
% length/ask questions
instr.time_train       = ['Die nun folgende Uebungsphase wird ca. 5 Minuten dauern. '...
                            '\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen. '...
                            '\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];


instr.time_exp         =  ['Das gesamte Experiment wird ca. 60 Minuten dauern. '...
                           '\n Es wird 3 Pausen geben in denen Sie sich kurz erholen koennen. '... 
                            '\n Sollten Sie noch Fragen haben, koennen Sie diese jetzt stellen. '...
                            '\n Wenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];

% break

instr.break_exp          = ['Sie haben jetzt ein (weiteres) Viertel geschafft. '... 
                            'Sie koennen eine kleine Pause machen und sich lockern.'];
                           








