%% Instructions IMT German
% =========================================================================
% TUE008 Version
% Corinna Schulz, August 2022
% =========================================================================

%% general

instr.text_coins1     = '1 Geldpunkt pro Druckstärkeeinheit';
instr.text_coins10    = '10 Geldpunkte pro Druckstärkeeinheit';
instr.text_cookies1   = '1 Essenspunkt pro Druckstärkeeinheit';
instr.text_cookies10  = '10 Essenspunkte pro Druckstärkeeinheit';

instr.press_GFD = 'Zum Starten drücken Sie kurz das Gerät.';
instr.continue_GFD = 'Für "Weiter" drücken Sie kurz das Gerät.';

%% =========================================================================
% RunLabel I: training section
% =========================================================================
instr.train_welcome_text = ['Willkommen.' ...
                            '\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und Snacks spielen' ...
                            '\nSie können sich zunächst mit den Funktionen vertraut machen und ein bisschen üben.' ...
                            '\nDas eigentliche Spiel wird dann im Scanner starten.'];

%% Calibration phase: estimation of max and min force 
instr.train_effort     = ['Auf dem Bildschirm werden Sie gleich ein nach oben geöffnetes Gefäss sehen mit einem blauen Ball darin.' ...
            '\nWenn Sie den Griff in Ihrer Hand zusammendrücken bewegt sich der Ball nach oben.' ...
            '\nJe fester Sie drücken, desto höher steigt der Ball.' ...
            '\nIn den nächsten Durchgängen sollen Sie sich mit dem Gerät vertraut machen.'...
            '\nBitte verändern Sie während des Versuchs Ihre Handhaltung nicht.' ...
              ];

instr.first_round_train  = ['Versuchen Sie in den nächsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie können.'];

instr.middle_round_train = ['Halten Sie das Gerät in den folgenden 10 Sekunden einfach nur locker in der Hand ohne zuzudrücken. '];                  

instr.last_round_train   = ['Versuchen Sie jetzt, den Ball noch höher steigen zu lassen als im ersten Versuch.'];

%% Conditioning phase


instr.intro_reward         = ['Sie können in den einzelnen Durchgängen unterschiedliche Gewinne erhalten.' ...
                            '\nSie spielen dabei sowohl für Geld als auch für Kalorien, '...
                            '\ndie Sie im Anschluss an die Aufgabe für einen Snack eintauschen können.'... 
                            '\nWas die aktuelle Belohnung ist bleibt für einen Durchgang konstant.' ... 
                            ];
                     
instr.reward_money         = ['In manchen Durchgängen können Sie Geld-Punkte gewinnen.'... 
                            '\nIm Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt.'...
                            '\n\nFolgende Bedingungen gibt es:\n\n\n', instr.text_coins1 '\n\n' instr.text_coins10 ];
                        
instr.reward_kcal         = ['In manchen Durchgängen können Sie Kalorien gewinnen.'...
                            ' \nIm Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben.'...
                            '\n\nFolgende Bedingungen gibt es: \n\n\n', instr.text_cookies1 '\n\n' instr.text_cookies10];

instr.tones     = ['In der späteren Aufgabe im Scanner werden Sie keinen Bildschirm haben.' ...
                            '\nDaher werden Sie in dieser Trainingsphase zunächst lernen welche Töne mit Geld- oder Essensbelohnungen, und mit '...
                            '\nvielen oder weniger Punkten assoziiert sind.']; 

instr.start_conditioning = ['Jetzt lernen Sie die Töne kennen, die Ihnen später im Scanner verraten,'...
    '\nfür welche Belohnung Sie in der Gebotsphase spielen. ' ...
    '\nSie werden zuerst den Ton hören'...
    '\nund daraufhin ein Bild sehen das für die dazugehörige Belohnung steht.'...
    '\nVersuchen Sie sich zu merken welcher Ton zu welcher Belohnung passt.']; 

instr.start_practice_conditioning = ['Nach einiger Zeit werden Sie dann in einer Testphase gebeten, ' ...
    '\nanzugegeben welche Bedingung zu welchem Ton gehört.' ...
    '\nIn diesen Testdurchgängen werden Sie die unterschiedlichen Töne erneut hören.' ...
    '\nAber diesesmal ohne die Bilder. In manchen Durchgängen werden Sie gebeten mittels der Pfeiltasten anzugeben,'...
    '\nob es sich um eine Essens- (Pfeil nach links) oder Geldbelohnung (Pfeil nach rechts) gehandelt hat.'...
    '\nIn anderen Durchgängen werden Sie gebeten mittels der Pfeiltasten anzugeben,' ...
    '\nob es sich um eine 1-fache (Pfeil nach unten) oder 10-fache (Pfeil nach oben) Belohnung handelt.' ...
    '\n\n\n Für diese Trainingsphase können Sie nach dem Weiter das Druckgerät beiseite legen.']; 

instr.start_queries = 'Start Testdurchgänge';

instr.test = 'Test';

instr.query_reward = 'Essen?                                      Geld?';
instr.query_magnitude = ['10-fach?'...
                    '\n\n '...
                    '\n\n1-fach?'];

instr.cue_feedback_correct = ['Korrekt!'];
instr.cue_feedback_wrong = ['Inkorrekt']; 

instr.done_conditioning = ['Sehr gut. Sie wissen nun welche Töne welche Belohnungen vorhersagen!'...
    '\nNehmen Sie nun wieder das Druckgerät in die Hand.']; 

instr.not_yet_there = ['Das war schon ganz gut. Wir üben aber nocheinmal,'... 
    '\ndamit Sie sich nacher im Experiment im Scanner sicher sind mit den Tönen.']; 

%% Full Training phase
instr.train_bidding = 'Jetzt üben wir das eigentliche Experiment.'; 

instr.train_bidding_recap = ['Sie hören zuerst einen Ton. In den darauffolgenden Gebots-Phasen geben Sie an, ' ...
    '\nwie viel Anstrengung Sie bereit sind auszugeben für die jeweilige Belohnung.' ...
    '\nDie Dauer einer Gebots-Phase beträgt ungefähr 3 Sekunden, variiert aber leicht. ' ...
    '\nAchtung: Die Gebotsphase started nach dem Ende eines Signal-Tones!'...
    '\nJe länger und stärker Sie gedrückt halten, desto mehr Druckeinheiten erhalten Sie für diese Runde. ' ...
    '\nDie Druckeinheiten werden dann je nach Belohnungsbedingung umgerechnet.'...
    ];


instr.time_strategy = ['Das gesamte Experiment wird später ca. 20 Minuten im Scanner dauern.' ...
                      '\nEs wird also nicht immer möglich sein, durchgehend zu drücken.'...
                      '\nEine Möglichkeit damit umzugehen, ist, auch während eines Durchganges Pausen zu machen'...
                      '\num danach wieder stärkeren Druck ausüben zu können.' ...
                      '\n Bitte halten Sie dabei die Hand so still wie möglich.']; 

%% =========================================================================
% Experiment in Scanner
% =========================================================================

instr.intro = 'Gleich startet die Experimentelle Aufgabe.';
instr.signal_tone = 'Wichtig! Drücken Sie erst nach dem Signal Ton!'; 
instr.signal_example = 'Sie hören jetzt den Signal Ton.'; 
instr.intro_scanner = 'Nun folgt eine kurze Erinnerung an die Tonbedinungen';
instr.intro_scanner_start = 'Start der Aufgabe'; 

instr.end_exp = ['Die Aufgabe ist nun zu Ende. '...
    'Bitte bleiben Sie noch still liegen bis wir zu Ihnen in den Raum kommen.']; 



                               