clear


path = pwd;
filename = 'EAT_Settings_BON006_S4_R1.mat';
load(filename);

instr.text_coins1 = '1 Geld-Punkt pro Sekunde';
instr.text_coins10 = '10 Geld-Punkte pro Sekunde';
instr.text_cookies1 = '1 Essens-Punkt pro Sekunde';
instr.text_cookies10 = '10 Essens-Punkte pro Sekunde';
instr.text_Cont = 'Weiter mit Druck.';
instr.text.A = 'Weiter mit A';
instr.train_welcome_text = 'Willkommen.\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben, bevor das eigentliche Spiel beginnt.';
instr.train_instr =  'Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess mit einem blauen Ball darin sehen. Wenn Sie die rechte Taste am Controller mit Ihrem Zeigefinger druecken, bewegt sich der Ball nach oben. Je schneller Sie druecken, desto hoeher steigt der Ball.\nSie haben jetzt zweimal 10 Sekunden Zeit, um den Ball so hoch wie moeglich steigen zu lassen.\nDie hoechste erreichte Position wird mit einer blauen Linie angezeigt.';
instr.first_round_train = 'Bitte veraendern Sie waehrend des Versuchs Ihre Handhaltung nicht.\n\nVersuchen Sie in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen.';
instr.last_round_train = 'Das war schon sehr gut. Versuchen Sie jetzt, den Ball noch hoeher steigen zu lassen.';
instr.train_instr_left = 'Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess mit einem blauen Ball darin sehen.  Wenn Sie den Griff in Ihrer Hand zusammendruecken, bewegt sich der Ball nach oben.  Je fester Sie druecken, desto hoeher steigt der Ball. \nIn den naechsten Durchgaengen sollen Sie sich mit dem Geraet vertraut machen. Bitte bewegen Sie sich waehrend der Messung nicht und veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels. \n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen, indem Sie den Griff in Ihrer LINKEN Hand drücken.';
instr.second_round_train_left = 'Versuchen Sie in den folgenden 10 Sekunden noch einmal den Ball so hoch wie moeglich steigen zu lassen. \nBenutzen Sie hierfür noch einmal den Griff in Ihrer LINKEN Hand.';
instr.first_round_train_right =  'Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess mit einem blauen Ball darin sehen.  Wenn Sie den Griff in Ihrer Hand zusammendruecken, bewegt sich der Ball nach oben.  Je fester Sie druecken, desto hoeher steigt der Ball. \nIn den naechsten Durchgaengen sollen Sie sich mit dem Geraet vertraut machen. Bitte bewegen Sie sich waehrend der Messung nicht und veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels. \n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen, indem Sie den Griff in Ihrer RECHTEN Hand drücken.';
instr.second_round_train_right = 'Versuchen Sie in den folgenden 10 Sekunden noch einmal den Ball so hoch wie moeglich steigen zu lassen. \nBenutzen Sie hierfür noch einmal den Griff in Ihrer RECHTEN Hand.';
instr.middle_round_train = 'Halten Sie das Geraet in dem folgenden Durchgang einfach nur locker in den Haenden ohne zuzudruecken.';
%for grip fore device
instr.strt_actual_train = 'Jetzt ueben Sie die eigentliche Aufgabe:\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen. Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert. \n\nDie nun folgende Uebungsphase wird ca. 5 Minuten dauern. Bitte benutzen Sie das Geraet in Ihrer RECHTEN Hand und versuchen Sie in dieser Übung den Ball möglichst bei jedem Trial möglichst lange über der Linie zu halten.';
%for gamepad
instr.strt_actual_train2 = 'Jetzt ueben Sie die eigentliche Aufgabe:\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber eine rote Linie zu bewegen. Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.';
%for grip force device
instr.intro_exp1 = 'Wir beginnen in der nächsten MRT Messung mit dem Spiel, dass Sie vorhin geübt haben. Zur Erinnerung: Sie können Punkte gewinnen für jede volle Sekunde, die der Ball über der roten Linie bleibt. Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. Es wird also nicht immer möglich sein, den Ball die ganze Zeit vollständig über der Linie zu halten. Eine Möglichkeit damit umzugehen, ist, auch während eines Durchgangs Pausen zu machen um danach wieder fester drücken zu können. Das gesamte Experiment wird ca. 20 Minuten dauern. Bitte benutzen Sie das Geraet in Ihrer RECHTEN Hand.';
%for gamepad
instr.intro_exp2 ='Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben. Zur Erinnerung: dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber die rote Linie zu bewegen. Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.';
instr.reward_nr1 = 'Sie koennen in den einzelnen Durchgaengen unterschiedliche Gewinne erhalten. Sie spielen dabei sowohl fuer Geld als auch fuer Kalorien, die Sie im Anschluss an die Aufgabe fuer einen Snack eintauschen koennen. Was die aktuelle Belohnung ist, bleibt fuer einen Durchgang von 30 Sekunden konstant und wird Ihnen mit Hilfe von Bildern angezeigt.';
instr.reward_nr2 = 'In manchen Durchgaengen koennen Sie Geld-Punkte gewinnen. Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt.\n\nFolgende Bedingungen gibt es:';
instr.reward_nr3 = 'In manchen Durchgaengen koennen Sie Kalorien gewinnen. Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben.\n\nFolgende Bedingungen gibt es:';
instr.diff_nr1 = 'Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. Es wird also nicht immer moeglich sein, den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. Eine Moeglichkeit damit umzugehen, ist, auch waehrend eines Durchgangs Pausen zu machen um danach wieder schneller druecken zu koennen.';
instr.diff_exp = 'Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. Es wird also nicht immer moeglich sein, den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. Eine Moeglichkeit damit umzugehen ist, auch waehrend eines Durchgangs Pausen zu machen, um danach wieder schneller druecken zu koennen.';
% also for MRI??? 'Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. Es wird also nicht immer moeglich sein, den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. Eine Moeglichkeit damit umzugehen ist, auch waehrend eines Durchgangs Pausen zu machen, um danach wieder schneller druecken zu koennen.'
instr.vas_nr1 = 'Nach jedem Durchgang werden Ihnen nacheinander zwei Fragen angezeigt:\n\n"Wie stark haben Sie sich in diesem Durchgang verausgabt?" \n "Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten?"';
instr.vas_nr2 = 'Sie koennen zum Antworten den Regler auf einer Skala (ueberhaupt nicht - sehr) verschieben.  Nutzen Sie dazu bitte den linken Joystick auf dem Controller. Ihre Antwort müssen Sie dann mit der gruenen A-Taste auf dem Controller bestaetigen. Bitte beachten Sie, dass Sie fuer die Antworten nur eine begrenzte Zeit zur Verfuegung haben.  Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan.  Es gibt dabei kein "Richtig" oder "Falsch".';
instr.time_train = 'Die nun folgende Uebungsphase wird ca. 5 Minuten dauern.\nSollten Sie noch Fragen haben,  koennen Sie diese jetzt stellen.\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.';
instr.time_exp = 'Das gesamte Experiment wird ca. 30 Minuten dauern.\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen.\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.\nBitte denken Sie daran, das Geraet in Ihrer RECHTEN Hand zu benutzen.';
instr.time_exp2 = 'Das gesamte Experiment wird ca. 20 Minuten dauern.\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen.\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.';
instr.intro_exp3 = 'Der Unterschied zur Uebung vorhin ist, dass wir gleichzeitig zur Aufgabe die Vagusnerv-Stimulation am Ohr durchfuehren. Jeder Durchgang wird zusammen mit der Stimulation starten.';
instr.pinata = 'Versuchen Sie jetzt nochmal mit der RECHTEN Hand so fest zu drücken, dass der Ball ueber die Linie steigt, wenn Sie es schaffen, duerfen Sie sich einen Snack aus unserem Korb aussuchen';


instr_en.text_coins1 = '1 Money point per second';
instr_en.text_coins10 = '10 Money points per second';
instr_en.text_cookies1 = '1 Snack point per second';
instr_en.text_cookies10 = '10 Snack points per second';
instr_en.text_Cont = 'Continue with pressure.';
instr_en.text.A = 'Continue with A';
instr_en.train_welcome_text = 'Welcome.\n\nThis is a simple game where you will be playing for money and snacks.\nFor now, you can make yourself comfortable with the functions of the game and practice, before the actual experiment starts.';
instr_en.train_instr = 'On the screen you will see an open container with a blue ball inside. If you press the right button on the controller with your index finger, the ball will move upwards. The faster you press, the higher the ball rises.\nYou will have twice times 10 seconds now to make the ball rise as high as possible.\nThe highest position reached is indicated by a blue line';
instr_en.first_round_train = 'Please do not change your hand position during the experiment.\n\nTry to make the ball rise as high as you can in the next 10 seconds';
instr_en.last_round_train = 'That was already very good. Now try to make the ball rise even higher';
instr_en.train_instr_left = 'On the screen, you will see an open container with a blue ball inside. When you press the grip force device, the ball will move up. The harder you press the device, the higher the ball will rise. \nIn the next trials you should familiarize yourself with the device. Please do not move during the measurement and do not change your hand position during the game. \n\nYou will now have 10 seconds to move the ball as high as possible by pressing the device in your LEFT hand.';
instr_en.second_round_train_left =  'In the following 10 seconds, try to let the ball rise as high as possible. \nUse the device in your LEFT hand again.';
instr_en.first_round_train_right = 'On the screen, you will see an open container with a blue ball inside. When you press the grip force device, the ball will move up. The harder you press the device, the higher the ball will rise. \nIn the next trials you should familiarize yourself with the device. Please do not move during the measurement and do not change your hand position during the game. \n\nYou will now have 10 seconds to move the ball as high as possible by pressing the device in your RIGHT hand.';
instr_en.second_round_train_right = 'In the following 10 seconds, try to let the ball rise as high as possible. \nUse the device in your RIGHT hand again.';
instr_en.middle_round_train = 'In the next trial, please hold the device loosely in your hand without pressing';
instr_en.strt_actual_train = 'You will now practice the actual task:\n\nThe line will no longer move with the ball, but instead you should try to move the ball up and over the red line by pressing the device. You can win points for each full second that the ball is over the red line. You can tell when you are collecting points when the ball changes its color to light blue.\n\nThe following training phase will take about 5 minutes. Please use the device in your RIGHT hand and try to keep the ball above the line for as long as possible during each trial.';
instr_en.strt_actual_train2 = 'you will now practise the actual task:\nThe line will no longer move with the ball, but instead you should try to move the ball up and over a red line by pressing the button. You can win points for each full second that the ball is over the red line. You can tell when you are collecting points when the ball changes its color to light blue';
instr_en.intro_exp1 = 'We will start in the following MRI measurement the actual game that you practised earlier. As a reminder, You can win points for each full second that the ball is over the red line. During the experiment there will be different levels of difficulty. It will not always be possible to keep the ball the whole time over the red line. One way of dealing with this is to take breaks during a trial so that you can press stronger again afterwards. The whole experiment will take about 20 minutes. Please use the device in your RIGHT hand.';
instr_en.intro_exp2 = 'We will now start the actual game that you practised earlier. As a reminder, this is a simple game where you play for money and a snack.\n\nTry to move the ball up and over the red line by pressing the button. You can win points for every full second the ball is over the red line. You can tell when you are collecting points when the ball changes its color to light blue.';
instr_en.reward_nr1 = 'You can receive different types of reward  in the individual trials. You will play for money as well as for calories, which you can exchange for a snack at the end of the task. What the current reward is remains constant for 30 seconds and is shown to you with the help of pictures';
instr_en.reward_nr2 = 'In some trials you can win money points. At the end of the task you will be paid out the corresponding amount of money.\n\nThe following conditions apply:';
instr_en.reward_nr3 = 'In some trials you can win calories, which can be exchanged for snacks at the end of the task.\n\nThe following conditions apply:';
instr_en.diff_nr1 = 'During the experiment there will be different levels of difficulty. It will not always be possible to keep the ball the whole time over the red line. One way of dealing with this is to take breaks during a trial so that you can press faster again afterwards';
instr_en.diff_exp = 'As a Reminder: During the experiment there will be different levels of difficulty. It will not always be possible to keep the ball the whole time over the red line. One way of dealing with this is to take breaks during a trial so that you can press faster again afterwards';
instr_en.vas_nr1 = 'After each trial, there will be two questions shown:\n\n ‘How hard did you try in this trial?’ \n ‘How much did you want to receive the reward in this trial?';
instr_en.vas_nr2 = 'To answer you can move the controller on a scale (not at all - very).  To do this, please use the left joystick on the controller. You must then confirm your answer by pressing the green A button on the controller. Please note that you only have a limited amount of time to answer the questions.  Therefore, do not think too long, but answer spontaneously.  There is no ‘RIGHT’ or ‘WRONG’ answer';
instr_en.time_train = 'The following training round will take about 5 minutes.\nIf you have any questions,  you can ask them right now.\nWhen you feel ready, we can begin the experiment.';
instr_en.time_exp = 'The whole experiment will take about 30 minutes.\nIf you have any questions, you can ask them now.\nIf you feel ready, we can start the experiment now.\nPlease remember to use the device in your RIGHT hand.';
instr_en.time_exp2 = 'The whole experiment will take about 20 minutes.\nIf you have any questions, you can ask them now.\nIf you feel ready, we can start the experiment now.';
instr_en.intro_exp3 = 'The difference to the previous run is that we will now stimulate the vagus nerve during the task.';
instr_en.pinata = 'Try again to move the ball up and and over the red line by pressing the device in your RIGHT hand. If you succeed, you can select a snack from our basket.';

save(filename, 'brk', 'file', 'i', 'instr', 'instr_en', 'MR_timings', 'name_file', 'settings', 'timings');


