%% Instructions WOF EAT (Seedcorn) German

% general

instr.text_coins1     = '1 Geld-Punkt pro Sekunde';
instr.text_coins10    = '10 Geld-Punkte pro Sekunde';
instr.text_cookies1   = '1 Essens-Punkt pro Sekunde';
instr.text_cookies10  = '10 Essens-Punkte pro Sekunde';

% how to jump through instructions
if settings.do_fmri == 0
    instr.text_Cont = 'Weiter mit Mausklick.';
else
    instr.text_Cont = 'Weiter mit Druck.'; 
end

% training

instr.train_welcome_text = ['Willkommen.' ...
                            '\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                            '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.' ...
                            'Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten.'];
                  
instr.train_instr        = ['Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess sehen mit einem blauen Ball darin.' ...
                            'Wenn Sie den Griff in Ihrer Hand zusammendruecken bewegt sich der Ball nach oben.' ... 
                            'Je fester Sie druecken, desto hoeher steigt der Ball.' ... 
                            '\nIn den naechsten drei Durchgaengen sollen Sie sich mit dem Geraet vertraut machen.'];
                  
instr.first_round_train  = ['Bitte veraendern Sie waehrend des Versuchs Ihre Handhaltung nicht.' ... 
                            '\n\nVersuchen Sie in den folgenden 10 Sekunden den Ball so hoch wie moeglich steigen zu lassen.'...
                            '\nDie hoechste erreichte Position wird mit einer blauen Linie angezeigt.'];

instr.first_round_train_mri = ['Willkommen.\n\nGleich startet wieder das Spiel, bei dem Sie fuer Geld und Snacks arbeiten sollen.'... 
                              '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.'... 
                              'Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten.' 
                              'Bitte bewegen Sie sich waehrend der Messung nicht und veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels.'...
                              '\n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen.'];
           

        
instr.middle_round_train = 'Halten Sie das Geraet in den folgenden 10 Sekunden einfach nur locker in der Hand ohne zuzudruecken.';                  
                  
instr.last_round_train   = 'Versuchen Sie in den folgenden 10 Sekunden noch einmal den Ball so hoch wie moeglich steigen zu lassen.';


% bidding section
           
%!! pending

% experimental phase

instr.strt_actual_train  = ['Jetzt ueben Sie die eigentliche Aufgabe:' ... 
                            '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.' ... 
                            '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
                        
instr.strt_actual_train_mri = ['Jetzt ueben Sie die eigentliche Aufgabe:'... 
                            '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.'...
                            '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.'...
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.'...
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'...
                            '\n\nDie nun folgende Uebungsphase wird ca. 5 Minuten dauern.'];   
                        
instr.intro_exp1         = ['Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben. '...
                            'Zur Erinnerung: Dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                            '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
                                             
instr.intro_exp2         = ['Der Unterschied zur Uebung vorhin ist, dass Sie nicht in jedem Durchgang wissen werden, wo die Linie genau liegt.' ... 
                            'In der Haelfte der Durchgaenge sehen Sie stattdessen einen roten Bereich.' ...
                            'Die Linie, die der Ball uebersteigen muss um Punkte zu gewinnen, liegt irgendwo in diesem Bereich.'...
                            'Wenn Sie den Ball also komplett ueber diesen Bereich bewegen, sammeln Sie auf jeden Fall Essens- oder Geld-Punkte.'...
                            'In diesen Durchgaengen aendert der Ball seine Farbe nicht.' ...
                            '\n\n Wie zuvor sehen Sie jedoch nach dem Durchgang, wie viele Punkte Sie gesammelt haben. '...
                            'Dann wird Ihnen auch die tatsaechliche Position der Linie angezeigt.'];

% rewards

instr.reward_nr1         = ['Sie koennen in den einzelnen Durchgaengen unterschiedliche Gewinne erhalten.' ...
                            'Sie spielen dabei sowohl fuer Geld als auch fuer Kalorien, '...
                            'die Sie im Anschluss an die Aufgabe fuer einen Snack eintauschen koennen.'... 
                            'Was die aktuelle Belohnung ist bleibt fuer einen Durchgang von 24 Sekunden konstant' ... 
                            'und wird Ihnen mit Hilfe von Bildern angezeigt.'];
                        
instr.reward_nr2         = ['In manchen Durchgaengen koennen Sie Geld-Punkte gewinnen.'... 
                            'Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt.'...
                            '\n\nFolgende Bedingungen gibt es:'];
                       
instr.reward_nr3         = ['In manchen Durchgaengen koennen Sie Kalorien gewinnen.'...
                            'Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben.'...
                            '\n\nFolgende Bedingungen gibt es:'];
                        
    %here the text still needs to be adjusted so that the points and kcals
    %are the ones that come out of the computation from the bidding phase
instr.reward_nr4         =  ['Die Umrechnung der Punkte richtet sich nach folgendem Kurs:'...  
                            '\n6 Geld-Punkte entsprechen 1 Cent.'...
                            '\n\n6 Essens-Punkte entsprechen 1 Kcal.'...
                            '\n\nIm Anschluss an die Aufgabe koennen Sie die Geldpunkte in einen entsprechenden Geldbetrag eintauschen'...
                            'und fuer die Essens-Punkte einen entsprechenden Snack erhalten.'];
                        
% difficulty

instr.diff_train         =  ['Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            'Es wird also nicht immer moeglich sein,'... 
                            'den Ball die ganze Zeit vollstaendig ueber der Linie zu halten.'... 
                            'Eine Moeglichkeit damit umzugehen ist,'... 
                            'auch waehrend eines Durchgangs Pausen zu machen,'... 
                            'um danach wieder staerkeren Druck ausueben zu koennen.'];

instr.diff_exp           =  ['Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            'Es wird also nicht immer moeglich sein,' 
                            'den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. '
                            'Eine Moeglichkeit damit umzugehen ist,' 
                            'auch waehrend eines Durchgangs Pausen zu machen,'
                            'um danach wieder staerkeren Druck ausueben zu koennen.']; 
                        
% VAS Instructions

instr.VAS_instr          = ['Nach jedem Durchgang werden Ihnen nacheinander drei Fragen angezeigt:'...
                            '\n\n Wie stark haben Sie sich in diesem Durchgang verausgabt?'...
                            '\n  Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten?'...
                            '\n Wie glueklich fuehlen Sie sich im Moment?'...
                            '\n\nSie koennen zum Antworten den Regler auf einer Skala (ueberhaupt nicht - sehr) verschieben.'...
                            'Verwenden Sie bitte die Maus mit ihrer nicht-dominanten Hand.'... 
                            'Ihre Antwort muessen Sie dann mit einem Mausklick bestaetigen.'...
                            '\nBitte beachten Sie, dass Sie fuer die Antworten nur eine begrenzte Zeit zur Verfuegung haben.'...
                            'Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan.'...
                            'Es gibt dabei kein Richtig oder Falsch.'];
                        
                        
% Wheel of fortune related instructions                       
instr.wof_exp            = ['Ab und zu wird das Hauptspiel durch dem Gluecksradspiel unterbrochen,'... 
                            'in dem Sie Geld gewinnen oder verlieren koenen.'... 
                            '\n Hierfuer muessen Sie lediglich eine Taste druecken und es geht schon los.'];


instr.wof_panas          = ['Gleich am Anfang und auch zu vier weiteren Zeitpunkten werden wir Fragen zu ihrem Befinden stellen.'... 
                            '\n Hier haben Sie genau wie bei den Fragen nach jedem Durchgang nur eine begrenzte Zeit zur Verfuegung.'... 
                            '\n Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan.'... 
                            'Es gibt dabei kein Richtig oder Falsch.'];

                        
                        
                        
% length/ask questions
instr.length_train       = ['Die nun folgende Uebungsphase wird ca. 5 Minuten dauern.'...
                            '\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen.'...
                            '\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];


instr.length_exp         =  ['Das gesamte Experiment wird ca. 60 Minuten dauern.\n'... 
                            'Es wird 3 Pausen geben in denen Sie sich kurz erholen koennen.'... 
                            '\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen.'...
                            '\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];

% break

instr.break_exp          = ['Sie haben jetzt ein (weiteres) Viertel geschafft.'... 
                            'Sie koennen eine kleine Pause machen und sich lockern.']
                           
                        %'\n\n\n' num2str(15 - i_timer) '    Sekunden bis zur naechsten Runde.'];
                           % need to discuss whether it will continue
                           % automatically or depending on participant

instr.break_exp_mri      = ['Sie koennen jetzt fuer 5 Sekunden eine Pause machen und sich lockern.'...
                            '\n\n\n' num2str(5 - i_timer) '    Sekunden bis zur naechsten Runde.'];          



% VAS question text
%I (Emily) know that these questions are coded differently, but to make a
%fully language flexible version, they would also need to be in here
instr.VAS_wanted         = ['Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten?'];
instr.VAS_exhaused       = ['Wie stark haben Sie sich in diesem Durchgang verausgabt?'];
% I think "exerted" is a more accurate representation of "verausgabt". We
% should discuss this with Nils at some point
instr.VAS_happy          = ['Wie gluecklich fuehlen Sie sich im Moment?'];











% winning text

instr.win_money_trial          = ['Durchgang beendet.\n\nGewinn:   ' num2str(win_coins) '   Geld-Punkt(e).'];

instr.win_food_trial           = ['Durchgang beendet.!\n\nGewinn:   ' num2str(win_cookies) '   Essens-Punkt(e)'];

instr.win_final_training       = ['Die Uebung ist nun zu Ende.'...
                                '\n\n Im richtigen Spiel haetten Sie ' num2str(output.win.sum_coins) ' Geld-Punkte gewonnen. '...
                                '\n Das entspicht ' num2str(output.win.money) ' Euro. '...
                                '\n\nIm richtigen Spiel haetten Sie ' num2str(output.win.sum_cookies) ' Essens-Punkte gewonnen. '...
                                '\nDas entspricht ' num2str(output.win.kcal) ' Kcal.' ];


instr.win_final_exp            = ['Das Spiel ist nun zu Ende.'...
                                '\n\n Sie haben ' num2str(output.win.sum_coins) ' Geld-Punkte gewonnen. '...
                                '\n Das entspicht ' num2str(output.win.money) ' Euro.'...
                                '\n\nSie haben ' num2str(output.win.sum_cookies) ' Punkte fuer Essen gewonnen.'...
                                '\n Das entspricht ' num2str(output.win.kcal) ' Kcal. '...
                                '\n Sie erhalten ' num2str(output.win.snacks) ' Snacks als Gewinn.'];
                            
instr.win_final_exp            = ['Das Spiel ist nun zu Ende.'...
                                '\n\n Sie haben ' num2str(output.win.sum_coins) ' Geld-Punkte gewonnen. '...
                                '\n Das entspicht ' num2str(output.win.money) ' Euro.'...
                                '\n\nSie haben ' num2str(output.win.sum_cookies) ' Punkte fuer Essen gewonnen.'...
                                '\n Das entspricht ' num2str(output.win.kcal) ' Kcal. '...
                                '\n Sie erhalten ' num2str(output.win.snacks) ' Snacks als Gewinn.'...
                                '\n Bitte bleiben Sie noch still liegen bis wir zu Ihnen in den Raum kommen.'];
                            
                            
% seconds till next trial

instr.waitsecs           = ['Naechste Runde: ' num2str(4 - ceil(i_timer))];




