function instr = generate_wof_instr(do_fmri)

    
%% Instructions WoF EAT (Seedcorn) German    

% general

instr.german.text_coins1     = '1 Geld-Punkt pro Sekunde';
instr.german.text_coins10    = '10 Geld-Punkte pro Sekunde';
instr.german.text_cookies1   = '1 Essens-Punkt pro Sekunde';
instr.german.text_cookies10  = '10 Essens-Punkte pro Sekunde';

% how to jump through instructions
if do_fmri == 0
    instr.german.text_Cont = 'Weiter mit Mausklick.';
else
    instr.german.text_Cont = 'Weiter mit Druck.'; 
end

% training

instr.german.train_welcome_text = ['Willkommen.' ...
                            '\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                            '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben. ' ...
                            'Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten.'];
                  
instr.german.train_instr        = ['Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess sehen mit einem blauen Ball darin. ' ...
                            ' Wenn Sie die rechte Taste am Controller mit Ihrem Zeigefinger druecken, bewegt sich der Ball nach oben. ' ... 
                            ' Je schneller Sie druecken, desto hoeher steigt der Ball. ' ... 
                            '\nSie haben jetzt zweimal 10 Sekunden Zeit, um den Ball so hoch wie moeglich steigen zu lassen.'];
                  
instr.german.first_round_train  = ['Bitte veraendern Sie waehrend des Versuchs Ihre Handhaltung nicht. ' ... 
                            '\n\nVersuchen Sie in den folgenden 10 Sekunden den Ball so hoch wie moeglich steigen zu lassen. '...
                            '\nDie hoechste erreichte Position wird mit einer blauen Linie angezeigt.'];

instr.german.first_round_train_mri = ['Willkommen.\n\nGleich startet wieder das Spiel, bei dem Sie fuer Geld und Snacks arbeiten sollen. '... 
                              '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben. '... 
                              'Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten. ' ...
                              'Bitte bewegen Sie sich waehrend der Messung nicht und veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels. '...
                              '\n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen. '];

instr.german.middle_round_train = 'Halten Sie das Geraet in den folgenden 10 Sekunden einfach nur locker in der Hand ohne zuzudruecken. ';                  
                  
instr.german.last_round_train   = 'Versuchen Sie in den folgenden 10 Sekunden noch einmal den Ball so hoch wie moeglich steigen zu lassen. ';


% bidding section
           
instr.german.bidding            = ['Die folgenden Durchgaengen dienen dazu, die Aufgabe fuer Sie individuell anzupassen. ' ...
                            '\nIn mehreren Durchgaengen sehen Sie auf dem Bildschirm unterschiedliche Optionen, ' ...
                            'die Sie in diesem Spiel gewinnen koennen. \n\nDie Euromuenzen zeigen Geldbetraege an, '...
                            'die Schokoriegel zeigen Snacks an. Geben Sie in den darauffolgenden Gebots-Phasen an, ' ...
                            'wie viel Anstrengung Sie bereit waeren auszugeben, um die angezeigten Optionen zu gewinnen.' ...
                            '\nDie Dauer einer Gebots-Phase betraegt ungefaehr 3 Sekunden, variiert aber leicht. ' ...
                            'Versuchen Sie den Ball auf der Hoehe zu halten, die Sie zu “bieten” beabsichtigen.'];  

% experimental phase

instr.german.strt_actual_train  = ['Jetzt ueben Sie die eigentliche Aufgabe: ' ... 
                            '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen. ' ... 
                            '\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber eine rote Linie zu bewegen. ' ... 
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. ' ... 
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
                        
instr.german.strt_actual_train_mri = ['Jetzt ueben Sie die eigentliche Aufgabe: '... 
                            '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen. '...
                            '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen. '...
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. '...
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert. '...
                            '\n\nDie nun folgende Uebungsphase wird ca. 5 Minuten dauern.'];   
                        
instr.german.intro_exp1         = ['Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben. '...
                            'Zur Erinnerung: Dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                            '\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber eine rote Linie zu bewegen. ' ... 
                            'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. ' ... 
                            'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
                                             
instr.german.intro_uncer        = ['Der Unterschied zur Uebung vorhin ist, dass Sie nicht in jedem Durchgang wissen werden, wo die Linie genau liegt. ' ... 
                            'In der Haelfte der Durchgaenge sehen Sie stattdessen einen roten Bereich. ' ...
                            'Die Linie, die der Ball uebersteigen muss um Punkte zu gewinnen, liegt irgendwo in diesem Bereich. '...
                            'Wenn Sie den Ball also komplett ueber diesen Bereich bewegen, sammeln Sie auf jeden Fall Essens- oder Geld-Punkte. '...
                            'In diesen Durchgaengen aendert der Ball seine Farbe nicht. ' ...
                            '\n\n Wie zuvor sehen Sie jedoch nach dem Durchgang, wie viele Punkte Sie gesammelt haben. '...
                            'Dann wird Ihnen auch die tatsaechliche Position der Linie angezeigt.'];

% rewards

instr.german.reward_nr1         = ['Sie koennen in den einzelnen Durchgaengen unterschiedliche Gewinne erhalten. ' ...
                            'Sie spielen dabei sowohl fuer Geld als auch fuer Kalorien, '...
                            'die Sie im Anschluss an die Aufgabe fuer einen Snack eintauschen koennen. '... 
                            'Was die aktuelle Belohnung ist bleibt fuer einen Durchgang von 24 Sekunden konstant ' ... 
                            'und wird Ihnen mit Hilfe von Bildern angezeigt.'];
                        
instr.german.reward_nr2         = ['In manchen Durchgaengen koennen Sie Geld-Punkte gewinnen. '... 
                            'Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt. '...
                            '\n\nFolgende Bedingungen gibt es:'];
                       
instr.german.reward_nr3         = ['In manchen Durchgaengen koennen Sie Kalorien gewinnen. '...
                            'Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben. '...
                            '\n\nFolgende Bedingungen gibt es: '];
                        
 
% difficulty

instr.german.diff_nr1           =  ['Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. '...
                            'Es wird also nicht immer moeglich sein, '... 
                            'den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. '... 
                            'Eine Moeglichkeit damit umzugehen ist, '... 
                            'auch waehrend eines Durchgangs Pausen zu machen, '... 
                            'um danach wieder schneller druecken zu koennen.'];

instr.german.diff_exp           =  ['Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben. '...
                            'Es wird also nicht immer moeglich sein, ' ...
                            'den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. ' ...
                            'Eine Moeglichkeit damit umzugehen ist, ' ...
                            'auch waehrend eines Durchgangs Pausen zu machen, ' ...
                            'um danach wieder schneller druecken zu koennen.']; 
                        
% VAS Instructions

instr.german.vas_nr1          = ['Nach jedem Durchgang werden Ihnen nacheinander drei Fragen angezeigt: '...
                            '\n\n Wie stark haben Sie sich in diesem Durchgang verausgabt? '...
                            '\n  Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten? '...
                            '\n Wie gluecklich fuehlen Sie sich im Moment? '...
                            '\n\nSie koennen zum Antworten den Regler auf einer Skala (ueberhaupt nicht - sehr) verschieben. '... 
                            ' Nutzen Sie dazu bitte den linken Joystick auf dem Controller.'...
                            'Ihre Antwort muessen Sie dann mit der gruenen A-Taste auf dem Controller bestaetigen. '...
                            '\nBitte beachten Sie, dass Sie fuer die Antworten nur eine begrenzte Zeit zur Verfuegung haben. '...
                            'Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan. '...
                            'Es gibt dabei kein Richtig oder Falsch.'];
                        
                        
% Wheel of fortune related instructions      
instr.german.wof_train          = ['Als naechstes ueben wir ein weiteres Spiel mit einem Gluecksrad, '... 
                            '\n in dem Sie Geld gewinnen oder verlieren koennen. '...  
                            '\n  Waehrend dem Hauptteil des Experimentes wird die andere Aufgabe, '... 
                            'die Sie gerade geuebt haben manchmal von diesem Gluecksradspiel unterbrochen. '... 
                            '\n  Am Ende werden alle Gewinne und Verluste aus dem Spiel zusammenrechnet. '... 
                            '\n  Das Ergebnis dieser Uebungsrunde zaehlt allerdings nicht dazu. '];
                        
instr.german.wof_exp            = ['Ab und zu wird das Hauptspiel durch das Gluecksradspiel unterbrochen, '... 
                            'in dem Sie Geld gewinnen oder verlieren koennen. '... 
                            '\n Hierfuer muessen Sie lediglich die linke Maustaste druecken und es geht schon los.'];
                            
instr.german.wof_panas          = ['Gleich am Anfang und auch zu vier weiteren Zeitpunkten werden wir Fragen zu Ihrem Befinden stellen. '... 
                            '\n Hier haben Sie genau wie bei den Fragen nach jedem Durchgang nur eine begrenzte Zeit zur Verfuegung. '... 
                            '\n Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan. '... 
                            'Es gibt dabei kein Richtig oder Falsch.'];

                        
                        
                        
% length/ask questions
instr.german.time_train       = ['Die nun folgende Uebungsphase wird ca. 5 Minuten dauern. '...
                            '\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen. '...
                            '\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];


instr.german.time_exp         =  ['Das gesamte Experiment wird ca. 60 Minuten dauern. '...
                           '\n Es wird 3 Pausen geben, in denen Sie sich kurz erholen koennen. '... 
                            '\n Sollten Sie noch Fragen haben, koennen Sie diese jetzt stellen. '...
                            '\n Wenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];

% break

instr.german.break_exp          = ['Sie haben jetzt ein (weiteres) Viertel geschafft. '... 
                            'Sie koennen eine kleine Pause machen und sich lockern.'];

%% Instructions WoF EAT (Seedcorn) English    

% general

instr.english.text_coins1     = '1 Money point per second';
instr.english.text_coins10    = '10 Money points per second';
instr.english.text_cookies1   = '1 Snack point per second';
instr.english.text_cookies10  = '10 Snack points per second';

% how to jump through instructions
if do_fmri == 0
    instr.english.text_Cont = 'Continue with mouse click.';
else
    instr.english.text_Cont = 'Continue by pressing.'; 
end

% training

instr.english.train_welcome_text = ['Welcome.' ...
                            '\n\nThis is a simple game where you will be playing for money and snacks.' ...
                            '\nYou can make yourself comfortable with the functions of the game and practice. ' ...
                            'The actual experiment will start at a later time.'];
                  
instr.english.train_instr        = ['On the screen, you will see an open container with a blue ball inside.' ...
                            ' When you press the right button on the controller with your index finger, the ball will move up.' ... 
                            ' The faster you press the button, the higher the ball will rise.' ... 
                            '\nYou will have 10 seconds to move the ball as high as possible.'];
                  
instr.english.first_round_train  = ['Please do not change how you hold the controller during the game.' ... 
                            '\n\nIn the following 10 seconds, try to move the ball as high as you possibly can.'...
                            '\nThe highest point the ball reaches will be marked with a blue line.'];

instr.english.first_round_train_mri = ['Welcome.\n\nThe game where you will be working for money and snacks will start soon.'... 
                              '\nYou can make yourself comfortable with the functions of the game and practice.'... 
                              'The actual experiment will start at a later time.' ...
                              'Please do not move during the measurement and please do not change your hand position during the game.'...
                              '\n\nIn the first 10 seconds, try to move the ball as high as you possibly can.'];

instr.english.middle_round_train = 'In the following 10 seconds, just hold the device in your hand without squeezing.';                  
                  
instr.english.last_round_train   = 'In the following 10 seconds, try to move the ball as high as you possibly can.';


% bidding section
           
instr.english.bidding            = ['The following trials serve to adapt the task specifically to you. ' ...
                            '\nIn the trials, you will see the different options on the screen' ...
                            'that you can win in the game. \n\nThe coins represent money '...
                            'the chocolate bars represent snacks. Show in the following bidding phase ' ...
                            'how much effort you are willing to exert to win the options shown on the screen.' ...
                            '\nThe duration of the bidding phase is about 3 seconds, but this will vary a little.' ...
                            'Try to keep the ball at the level of effort at which you are willing to "offer."'];  

% experimental phase

instr.english.strt_actual_train  = ['You will now practice the actual task: ' ... 
                            '\nThe line will now not move with the ball. ' ... 
                            '\n\nBy repeatedly pressing the button on the controller, try moving the ball up and above the red line. ' ... 
                            'You can win points for each full second that the ball is above the red line. ' ... 
                            'You can tell when you are collecting points when the ball changes its color to light blue.'];
                        
instr.english.strt_actual_train_mri = ['You will now practice the actual task: '... 
                            '\nThe line will now not move with the ball. ' ... 
                            '\n\nBy squeezing the device, try moving the ball up and above the red line. '...
                            'You can win points for each full second that the ball is above the red line. ' ... 
                            'You can tell when you are collecting points when the ball changes its color to light blue.'...
                            '\n\nThe following practice phase will take about 5 minutes.'];   
                        
instr.english.intro_exp1         = ['We will now begin the game that you practiced earlier. '...
                            'As a reminder: This is a simple game where you will be playing for money and snacks.' ...
                            '\n\nBy repeatedly pressing the button on the controller, try moving the ball up and above the red line. ' ... 
                            'You can win points for each full second that the ball is above the red line. ' ... 
                            'You can tell when you are collecting points when the ball changes its color to light blue.'];
                                             
instr.english.intro_uncer        = ['The difference from the practice phase earlier is that you will not know in every trial where the line exactly is. ' ... 
                            'In those trials, you will see a red area instead. ' ...
                            'The line you need to cross to win points will be somewhere within that area. '...
                            'So if you move the ball completely above the read area, you will definitely collect the money or snack points. '...
                            'In these trials, the ball will not change color. ' ...
                            '\n\n Just as before, you will see the number of points you win at the end of each trial. '...
                            'Then you will be shown the actual position of the line.'];

% rewards

instr.english.reward_nr1         = ['You can win different rewards in each of the trials. ' ...
                            'You will be playing for both money and calories, '...
                            'which you can trade in for snacks at the end of the task. '... 
                            'The current reward will stay constant for each of the 24 second trials ' ... 
                            'and will be shown to you as pictures on the screen. '];
                        
instr.english.reward_nr2         = ['In some trials, you can win money points. '... 
                            'Following the task, the amount corresponding to your money points will be paid out. '...
                            '\n\nThe following conditions are:'];
                       
instr.english.reward_nr3         = ['In some trials, you can win calories. '...
                            'Following the task, you will receive the corresponding number of snacks. '...
                            '\n\nThe following conditions are: '];
                        
 
% difficulty

instr.english.diff_nr1           =  ['During the experiment, there will be different levels of difficulty. '...
                            'That means, it will not always be possible '... 
                            'to keep the ball fully above the line during the whole trial. '... 
                            'One possibility to deal with this is '... 
                            'to take breaks during the trials '... 
                            'such that you can then press the button faster. '];

instr.english.diff_exp           =  ['As a reminder: During the experiment, there will be different levels of difficulty. '...
                            'That means, it will not always be possible '... 
                            'to keep the ball fully above the line during the whole trial. '... 
                            'One possibility to deal with this is '... 
                            'to take breaks during the trials '... 
                            'such that you can then press the button faster. '];
                        
% VAS Instructions

instr.english.vas_nr1          = ['After each trial, you will be shown three questions, one after the other: '...
                            '\n\n How strongly did you exert yourself in this trial? '...
                            '\n  How much did you want the reward shown in this trial? '...
                            '\n How happy do you currently feel? '...
                            '\n\nTo answer each question, you can move the point on the scale (not at all - very)'... 
                            ' Please use the left joystick to move the point. '...
                            'Use the green A-button to confirm your response. '...
                            '\nPlease be aware that you only have a limited time available to answer the questions. '...
                            'So do not think to long about the questions, but instead answer spontaneously. '...
                            'There is no right or wrong answer.'];
                        
                        
% Wheel of fortune related instructions      
instr.english.wof_train          = ['Next, you will play a practice round with the Wheel of Fortune'... 
                            '\n in which you can win or lose money. '...  
                            '\n  During the main part of the experiment, the task '... 
                            'that you just practiced will sometimes be interrupted with the Wheel of Fortune. '... 
                            '\n  At the end of the task, all wins and losses will be summed together. '... 
                            '\n  The result of this practice round will of course not count towards the total. '];
                        
instr.english.wof_exp            = ['Every now and then, the task will be interrupted by a Wheel of Fortune '... 
                            'in which you can win or lose money. '... 
                            '\n Here, you just need to press the left mouse button to start. '];
                            
instr.english.wof_panas          = ['Right at the beginning of the task and at four other time points, we will ask you several questions about how you feel. '... 
                            '\n For these questions, you will have a limited time to respond, just like the questions asked at the end of each trial. '... 
                            '\n So do not think to long about the questions, but instead answer spontaneously. '... 
                            'There is no right or wrong answer.'];

                        
                        
                        
% length/ask questions
instr.english.time_train       = ['The following practice phase will take about 5 minutes. '...
                            '\nIf you have questions, you can ask them now.  '...
                            '\nWhen you are ready, you can begin the experiment. '];


instr.english.time_exp         =  ['The whole experiment will take about 60 minutes. '...
                           '\n There will 3 breaks in which you can shortly rest. '... 
                            '\n If you have questions, you can ask them now. '...
                            '\n When you are ready, you can begin the experiment. '];

% break

instr.english.break_exp          = ['You have now completed a(nother) quarter of the trials.  '... 
                            'You can now take a short break and rest.'];



end






