%% General settings
clear
% Change flags to customize script
% subj struct
subj.version = 3; %Task version
subj.study = 'BON001';
subj.sessionID = '2';
subj.runID = '3';
subj.run = str2double(subj.runID);

%settings struct
settings.debug          = 0; % set to 1 for tests
settings.do_fullscreen  = 1; %will show window as fullscreen (default second monitor, if connected)
settings.do_gamepad     = 0;
settings.do_GFD         = 1; %will load specific parameters for the use uf the grip force device for bidding (scale)
settings.do_fmri        = 0; %will include trigger
settings.do_EGG         = 1; %will include gastrogram triggers
if settings.do_EGG
    settings.EGG.trigDur = 0.005; % duration for sending triggers in seconds
end
settings.do_VNS         = 1;  % stimulation (1) or not (0)
settings.lang_de        = 1; %changes display language to German

%% instructions while subject is waiting for the trigger

if settings.lang_de == 1

    if subj.run == 1

        instruct.text_p1 = ['In der folgenden Aufgabe sehen Sie in zufaelliger Abfolge entweder Bilder mit Essen ' ...
            '\n\n oder Bueromaterialien. Danach bitten wir Sie jeweils anzugeben, wie sehr Sie ' ...
            '\n\n das dargestellte Objekt als Belohnung in diesem Moment gern erhalten wuerden, ' ...
            '\n\n bzw. wie sehr Sie das dargestellte Objekt als Belohnung moegen. ' ...
            '\n\n Wie sehr Sie das Objekt erhalten wollen, bzw. moegen wird mittels verschiedener Skalen ' ...
            '\n\n abgefragt werden: Bitte nutzen Sie die horizontale Skala, um anzugeben, wie sehr Sie ' ...
            '\n\n die Belohnung in diesem Moment erhalten moechten und die vertikale Skala, um anzugeben, ' ...
            '\n\n wie sehr Sie die dargestellte Belohnung in diesem Moment moegen. ' ...
            '\n\n Welche Skala jeweils nach einem Bild erscheint, wird zufaellig ausgewaehlt. ' ...
            '\n\n Benutzen Sie die Maus, um auf dem Slider zu navigieren '...
            '\n\n und bestaetigen Sie Ihre Antworten anschließend mit einem Klick. '...
            '\n\n '...
            '\n\n Klicken Sie nun mit der Maus, um das Experiment zu starten.'
            ];


        instruct.text_p2 = [];

    elseif subj.run == 2

        instruct.text_p1 = ['In der folgenden Aufgabe sehen Sie auf dem Bildschirm in Bloecken ' ...
            '\n\n Bilder mit Essen oder Bueromaterialien. ' ...
            '\n\n Stellen Sie sich vor, die dargestellten Optionen sind verfuegbar, ' ...
            '\n\n wie beispielsweise bei einem Buffet. ' ...
            '\n\n Wenn Sie kein Fleisch oder Fisch essen, ' ...
            '\n\n stellen Sie sich vegetarische oder vegane Ersatzprodukte vor. ' ...
            '\n\n Geben Sie in den darauffolgenden Gebots-Phasen an, wie viel Anstrengung ' ...
            '\n\n Sie bereit waeren auszugeben, um Zugang zu den Optionen zu bekommen. ' ...
            '\n\n Die Dauer der Gebots-Phasen betraegt ungefaehr 5 Sekunden. ' ...
            '\n\n ' ...
            '\n\n Weiter mit Druck. '];

        instruct.text_p2 = ['Am Ende wird zufaellig ein Durchgang ausgewaehlt. ' ...
            '\n\n Ihr Gebot wird dann mit den Geboten anderer Spieler verglichen, um zu entscheiden, ' ...
            '\n\n ob Sie den Zuschlag bekommen. Je mehr Sie also "bieten", ' ...
            '\n\n desto wahrscheinlicher ist es, dass Sie den Block gewinnen. ' ...
            '\n\n Wenn Ihr Gebot ausreicht, koennen Sie sich am Ende des Termins durch Anstrengung ' ...
            '\n\n die Belohnung erarbeiten. ' ...
            '\n\n Sie koennen in jedem Durchgang frei entscheiden, mit welcher Hand Sie das Gebot abgeben. ' ...
            '\n\n ' ...
            '\n\n Weiter mit Druck. Die Aufgabe startet dann automatisch. '];

        instruct.text_lottery1 = ['Die Lotterie hat ergeben, dass die oben angezeigten Optionen zu erspielen sind. '...
            '\n\n '...
            '\n\n  Am Ende des heutigen Termins koennen Sie noch einmal einen Durchgang '...
            '\n\n spielen und Punkte gewinnen, die Sie im Anschluss fuer Belohnungen eintauschen koennen.'];

        instruct.text_lottery2 = ['Die Lotterie hat ergeben, dass die oben angezeigten Optionen zu erspielen sind. '...
            '\n\n'...
            '\n\n Leider reicht Ihr Gebot nicht aus. Sie koennen diesmal nichts gewinnen. '];


    elseif subj.run == 3

        instruct.text_p1 = ['Sie haben jetzt die Moeglichkeit, eine der unten '...
            '\n\n aufgefuehrten Optionen zu erwerben. Bewegen Sie dazu den Ball ueber '...
            '\n\n die angezeigte Schwelle, indem Sie das Geraet in Ihrer RECHTEN Hand druecken. ' ...
            '\n\n Wenn Sie es schaffen, den Ball bis zum Ende ueber der Schwelle zu halten,' ...
            '\n\n erhalten Sie am Ende der Sitzung eine der dargestellten Belohnungen. ' ...
            '\n\n Der Durchgang dauert ca. 30 Sekunden. Bitte benutzen Sie das Geraet in Ihrer RECHTEN Hand.' ...
            '\n\n ' ...
            '\n\n Weiter mit Druck. Die Aufgabe startet dann automatisch. '];

        instruct.text_p2 = [];
        %instruct.text_p2 = ['Weiter mit Druck'];
        instruct.bidding_win = 'Herzlichen Gluekwunsch!\n\n Sie haben eine der oben dargestellten Optionen gewonnen!';
        instruct.bidding_lost = 'Leider haben Sie nicht genuegend Druck aufgewendet.\n\n Heute haben Sie daher leider nichts gewonnen!';


    end

else
    instruct.text_p1 = [];
end

%% Electrogastrogram
if settings.do_EGG == 1

    % set trigger values for events
    settings.EGG.trigger.exp_on = 10;
    settings.EGG.trigger.image = 50;
    settings.EGG.trigger.image_end = 100;
    settings.EGG.trigger.scales.LHS = 120;
    settings.EGG.trigger.scales.LHS_end = 150;
    settings.EGG.trigger.scales.VAS = 160;
    settings.EGG.trigger.scales.VAS_end = 170;
    settings.EGG.trigger.scales.GFD = 180;
    settings.EGG.trigger.scales.GFD_end = 200;
    settings.EGG.trigger.exp_off = 255;

end

%% Save

name_file = strcat('FCRsettings_', subj.study, '_S', subj.sessionID, '_R', subj.runID);
save(name_file, 'instruct', 'name_file', 'settings')