%% save all study specific settings in .mat 
% choose name for .mat file
clear

%study information
subj.study             = 'TUE005';  % Project number
subj.sessionNR         = '1';
subj.runID             = '1'; 

%% Part 1: settings and study information

% settings
settings.do_fullscreen = 1;  % default second monitor, if connected
settings.do_fmri       = 1;  % will include trigger
settings.do_EGG        = 1;  % will include EGG trigger
settings.debug         = 0;  % input device not required
settings.do_gamepad    = 0;  % (1) for frequency, (0) for grip force
settings.do_WOF        = 0;  % include wheel of fortune
settings.do_VAS        = 0;  % include VAS
settings.do_val_cal    = 1;  % calibrate value difference between food/money
settings.use_val_cal   = 0;  % use calibrated value difference for food/money (txt file in data folder)
settings.do_timelimit  = 1;  % time limit for intermittent VAS questions
settings.lang_de       = 1;  % german. English when 0
settings.do_feedback   = 1;  % feedback on (1) or off (0)
settings.train_trials  = 2;  % amount of training trials to estimate max/min (2 or 3)
settings.do_VNS        = 1;  % stimulation (1) or not (0)
settings.load_max_sess = 1;  % session from which the maxEffort needs to be loaded
settings.do_uncertain  = 0;  % uncertainty used in paradigm (1) or not (0)

% Settings VAS
if settings.do_VAS == 1
    settings.VAS_input      = 0; % VAS input is 1 for joystick, 0 for mouse
    settings.VAS.exhaustion = 1;
    settings.VAS.wanting    = 1;
    settings.VAS.happy1     = 1;
    settings.VAS.happy2     = 0;
end

settings.value_money   = 32;    % amount of cents earned with 100 points
settings.value_food    = 32;    % amount of kcal earned with 100 points
settings.clckforce     = 20000; % only relevant for grip force device set-ups

%% Part 2: task timings

% Durations of  
if settings.do_fmri == 0
    timings.trial_length        = 24; 
    timings.break_length        = 15; 
    timings.feedback_length     = 2.5;
    timings.fix1_length         = 0;
    timings.fix2_length         = 1.5;
    timings.bidding_length      = 5;
    timings.VAS_rating_duration = 3.2; 
    timings.number_breaks       = 2;
    timings.number_trials       = 64;
    timings.avrg_jttr_ball      = '1';
    timings.avrg_jttr_fix1      = '1';
    timings.avrg_jttr_fix2      = '1';
    timings.max_jttr_ball       = '4';
    timings.max_jttr_fix1       = '12';
    timings.max_jttr_fix2       = '12';
elseif settings.do_fmri == 1
    timings.trial_length        = 30;
    timings.break_length        = 10;
    timings.feedback_length     = 2.5;
    timings.fix1_length         = 0.5;
    timings.fix2_length         = 1;
    timings.bidding_length      = 5;
    timings.number_breaks       = 2;
    timings.number_trials       = 48;
    timings.avrg_jttr_ball      = '1';
    timings.avrg_jttr_fix1      = '2';
    timings.avrg_jttr_fix2      = '3';
    timings.max_jttr_ball       = '4';
    timings.max_jttr_fix1       = '12';
    timings.max_jttr_fix2       = '12';
    %MR specific timings
    MR_timings.durations.effort     = timings.trial_length;
    MR_timings.durations.feedback   = timings.feedback_length;
    MR_timings.durations.win        = [];
    MR_timings.durations.rest_phase = [];
end

% determine before what trial breaks should be inserted
timings.break_trials = [];
for brk = 1:timings.number_breaks   
   breaknumbr           = timings.number_trials/(timings.number_breaks + 1)* brk;
   timings.break_trials = [timings.break_trials, round(breaknumbr)];
end
timings.break_trials = timings.break_trials + 1;

if settings.do_WOF == 1
    timings.nmbr_trls_to_WOF    = 6;
    timings.time_to_start       = 1; %Time to spin WOF from button press
    timings.show_wheel          = 5;
    timings.show_feedback       = 5;
    timings.PANAS_trials        = timings.break_trials - 1;   
    timings.PANAS_trials        = [timings.PANAS_trials, timings.number_trials];
end


%% Instructions
if settings.lang_de == 1 % German
% general

instr.text_coins1     = '1 Geld-Punkt pro Sekunde';
instr.text_coins10    = '10 Geld-Punkte pro Sekunde';
instr.text_cookies1   = '1 Essens-Punkt pro Sekunde';
instr.text_cookies10  = '10 Essens-Punkte pro Sekunde';

% how to jump through instructions
if settings.do_fmri == 0
    instr.text_Cont = 'Weiter mit Mausklick.';
else
    instr.text_Cont = 'Weiter mit Druck.'; 
end

% training

instr.train_welcome_text = ['Willkommen.' ...
                                '\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                                '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.' ...
                                ' Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten.'];

if settings.do_fmri == 1
    instr.train_instr        = ['Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess sehen mit einem blauen Ball darin.' ...
                                ' Wenn Sie den Griff in Ihrer Hand zusammendruecken bewegt sich der Ball nach oben.' ... 
                                ' Je fester Sie druecken, desto hoeher steigt der Ball.' ... 
                                '\nIn den naechsten zwei Durchgaengen sollen Sie sich mit dem Geraet vertraut machen.'...
                                'Bitte bewegen Sie sich waehrend der Messung nicht und '...
                                ' veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels.' ...
                                '\n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden ' ...
                                'den Ball so hoch steigen zu lassen, wie Sie koennen.'];
% elseif settings.do_fmri == 1
%     instr.train_instr        = ['Willkommen.\n\nGleich startet wieder das Spiel, bei dem Sie fuer Geld und Snacks arbeiten sollen. '...
%                                 '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.' ...
%                                 ' Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten. '... 
%                                 'Bitte bewegen Sie sich waehrend der Messung nicht und '...
%                                 ' veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels.' ...
%                                 '\n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden ' ...
%                                 'den Ball so hoch steigen zu lassen, wie Sie koennen.'];
end
                  
                  
instr.first_round_train  = ['Bitte veraendern Sie waehrend des Versuchs Ihre Handhaltung nicht.' ... 
                            '\n\nVersuchen Sie in den folgenden 10 Sekunden den Ball so hoch wie moeglich steigen zu lassen.'...
                            '\nDie hoechste erreichte Position wird mit einer blauen Linie angezeigt.'];

instr.first_round_train_mri = ['Willkommen.\n\nGleich startet wieder das Spiel, bei dem Sie fuer Geld und Snacks arbeiten sollen.'... 
                              '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.'... 
                              ' Das eigentliche Spiel wird dann zu einem spaeteren Zeitpunkt starten.' ...
                              ' Bitte bewegen Sie sich waehrend der Messung nicht und veraendern Sie Ihre Handhaltung nicht im Verlauf des Spiels.'...
                              '\n\nAls erstes versuchen Sie bitte in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen.'];
           

        
instr.middle_round_train = 'Halten Sie das Geraet in den folgenden 10 Sekunden einfach nur locker in der Hand ohne zuzudruecken.';                  
                  
instr.last_round_train   = 'Versuchen Sie in den folgenden 10 Sekunden noch einmal den Ball so hoch wie moeglich steigen zu lassen.';


% bidding section
           
instr.bidding            = ['Die folgenden Durchgaengen dienen dazu, die Aufgabe fuer Sie individuell anzupassen.' ...
                            '\nIn mehreren Durchgaengen sehen Sie auf dem Bildschirm unterschiedliche Optionen, ' ...
                            'die Sie in diesem Spiel gewinnen koennen. \n\nDie Euromuenzen zeigen Geldbetraege an, '...
                            'die Schokoriegel zeigen Snacks an. Geben Sie in den darauffolgenden Gebots-Phasen an, ' ...
                            'wie viel Anstrengung Sie bereit waeren auszugeben, um die angezeigten Optionen zu gewinnen.' ...
                            '\nDie Dauer einer Gebots-Phase betraegt ungefaehr 5 Sekunden, variiert aber leicht. ' ...
                            'Versuchen Sie den Ball auf der Hoehe zu halten, die Sie zu ?bieten? beabsichtigen.'];  

% experimental phase

if settings.do_fmri == 0
    instr.strt_actual_train  = ['Jetzt ueben Sie die eigentliche Aufgabe:' ... 
                                '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.' ... 
                                '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                                ' Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                                ' Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
elseif settings.do_fmri == 1
    instr.strt_actual_train  = ['Jetzt ueben Sie die eigentliche Aufgabe: ' ...
                                '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.' ...
                                '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen. '...
                                'Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt. ' ...
                                'Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert. '...
                                '\n\nDie nun folgende Uebungsphase wird ca. 5 Minuten dauern.'];                        
end                           

if settings.do_fmri == 0
    instr.intro_exp1         = ['Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben. '...
                                ' Zur Erinnerung: Dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                                '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                                ' Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                                ' Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
elseif settings.do_fmri == 1
    instr.intro_exp1         = ['Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben. '...
                                ' Zur Erinnerung: Dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                                '\n\nVersuchen Sie mithilfe von Druck den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                                ' Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.']; 
end

instr.intro_uncer         = ['Der Unterschied zur Uebung vorhin ist, dass Sie nicht in jedem Durchgang wissen werden, wo die Linie genau liegt.' ... 
                            ' In der Haelfte der Durchgaenge sehen Sie stattdessen einen roten Bereich.' ...
                            ' Die Linie, die der Ball uebersteigen muss um Punkte zu gewinnen, liegt irgendwo in diesem Bereich.'...
                            ' Wenn Sie den Ball also komplett ueber diesen Bereich bewegen, sammeln Sie auf jeden Fall Essens- oder Geld-Punkte.'...
                            ' In diesen Durchgaengen aendert der Ball seine Farbe nicht.' ...
                            '\n\n Wie zuvor sehen Sie jedoch nach dem Durchgang, wie viele Punkte Sie gesammelt haben. '...
                            ' Dann wird Ihnen auch die tatsaechliche Position der Linie angezeigt.'];
                        
instr.intro_tvns         = ['Der Unterschied zur Uebung vorhin ist, dass wir gleichzeitig zur Aufgabe die Vagusnerv-Stimulation am Ohr durchfuehren.' ...
                            ' Jeder Durchgang wird zusammen mit der Stimulation von der Versuchsleitung gestartet.'];

% rewards

instr.reward_nr1         = ['Sie koennen in den einzelnen Durchgaengen unterschiedliche Gewinne erhalten. ' ...
                            'Sie spielen dabei sowohl fuer Geld als auch fuer Kalorien, '...
                            'die Sie im Anschluss an die Aufgabe fuer einen Snack eintauschen koennen.'... 
                            ' Was die aktuelle Belohnung ist bleibt fuer einen Durchgang von 24 Sekunden konstant' ... 
                            ' und wird Ihnen mit Hilfe von Bildern angezeigt.'];
                        
instr.reward_nr2         = ['In manchen Durchgaengen koennen Sie Geld-Punkte gewinnen.'... 
                            ' Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt.'...
                            '\n\nFolgende Bedingungen gibt es:'];
                       
instr.reward_nr3         = ['In manchen Durchgaengen koennen Sie Kalorien gewinnen.'...
                            ' Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben.'...
                            '\n\nFolgende Bedingungen gibt es:'];
                        
                        
% difficulty

instr.diff_nr1           =  ['Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            ' Es wird also nicht immer moeglich sein,'... 
                            ' den Ball die ganze Zeit vollstaendig ueber der Linie zu halten.'... 
                            ' Eine Moeglichkeit damit umzugehen ist,'... 
                            ' auch waehrend eines Durchgangs Pausen zu machen,'... 
                            ' um danach wieder staerkeren Druck ausueben zu koennen.'];

instr.diff_exp           =  ['Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            ' Es wird also nicht immer moeglich sein,' ...
                            ' den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. ' ...
                            'Eine Moeglichkeit damit umzugehen ist,' ...
                            ' auch waehrend eines Durchgangs Pausen zu machen,' ...
                            ' um danach wieder staerkeren Druck ausueben zu koennen.']; 
                        
% VAS Instructions

instr.vas_nr1            = ['Nach jedem Durchgang werden Ihnen nacheinander drei Fragen angezeigt:'...
                            '\n\n Wie stark haben Sie sich in diesem Durchgang verausgabt?'...
                            '\n  Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten?'...
                            '\n Wie glueklich fuehlen Sie sich im Moment?'...
                            '\n\nSie koennen zum Antworten den Regler auf einer Skala (ueberhaupt nicht - sehr) verschieben.'...
                            ' Verwenden Sie bitte die Maus mit ihrer nicht-dominanten Hand.'... 
                            ' Ihre Antwort muessen Sie dann mit einem Mausklick bestaetigen.'...
                            '\nBitte beachten Sie, dass Sie fuer die Antworten nur eine begrenzte Zeit zur Verfuegung haben.'...
                            ' Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan.'...
                            ' Es gibt dabei kein Richtig oder Falsch.'];
                        
% length/ask questions

instr.time_train        = ['Die nun folgende Uebungsphase wird ca. 5 Minuten dauern.'...
                            '\nBitte melden Sie sich jetzt kurz bei der Versuchsleitung. Diese startet dann das Experiment fuer Sie.'];

if settings.do_fmri == 0
    instr.time_exp        = ['Das gesamte Experiment wird ca. 40 Minuten dauern.'...
                             '\nBitte melden Sie sich jetzt kurz bei der Versuchsleitung. Diese startet dann das Experiment fuer Sie.'];
elseif settings.do_fmri == 1
    instr.time_exp        = ['Das gesamte Experiment wird ca. 30 Minuten dauern.'...
                            '\nSollten Sie noch Fragen haben, koennen Sie diese jetzt stellen.'...
                            '\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];
end


elseif settings.lang_de == 0 % English
 
% general

instr.text_coins1     = '1 money point per second';
instr.text_coins10    = '10 money points per second ';
instr.text_cookies1   = '1 food point per second';
instr.text_cookies10  = '10 food points per second ';

% how to jump through instructions
if settings.do_fmri == 0
    instr.text_Cont = 'Continue with mouse click.';
elseif settings.do_fmri == 1
    instr.text_Cont = 'Continue by squeezing.';
end

% training
                   
instr.train_welcome_text = ['Welcome.' ...
                            '\n\nThis is a simple game in which you play for money and a snack.' ...
                            '\nYou can first familiarize yourself with the functions and practice. '...
                            'The actual game will start at a later time.'];
                         
if settings.do_fmri == 0
    instr.train_instr    = ['On the screen you will immediately see an open container with a blue ball in it. '...
                            'When you squeeze the device in your hand, the ball moves up. '...
                            'The harder you squeeze, the higher the ball rises.' ...
                            '\nIn the next three rounds, you should familiarize yourself with the device.'];

elseif settings.do_fmri == 1
    instr.train_instr    = ['Welcome.\n\nIn a few momemnts, the game will start in which you should work for money and snacks. '...
                                '\nYou can first familiarize yourself with the functions and practice. '...
                                ' The actual game will start at a later time. '...
                                'Please do not move during the measurement and '...
                                'change your overall hand position during the game.'...
                                '\n\nFirst, please try to get the ball as high up as you can in the next 10 seconds. '];
end
                            
instr.first_round_train  = ['Please do not change your hand position during the experiment. '...
                            '\n\nTry to get the ball as high up as possible in the next 10 seconds. '...
                            '\ nThe highest position reached is shown with a blue line.']; 

instr.first_round_train_mri = ['Welcome. \n\nNext, the game in which you should work with for money and snacks will start again. '...
                               '\nYou can first familiarize yourself with the functions and practice. '...
                               'The actual game will start at a later time. '...
                               'Please do not move during the measurement and do not change your overall hand position during the game. '...
                               '\n\nFirst, please try to get the ball as high up as you can in the next 10 seconds. '];                         

                           
                           
instr.middle_round_train = 'Hold the device loosely in your hand for the next 10 seconds without squeezing. ';
                  
instr.last_round_train   = 'Try once again to get the ball up as high as possible in the following 10 seconds. ';   


% bidding section

instr.bidding            = ['The following rounds serve to adapt the task individually for you. '...
                           '\nIn several rounds, you will see different options on the screen ' ...
                           'that you can win in this game. \n\ nThe euro coins show monetary amounts, '...
                           'the chocolate bars show snacks. In the subsequent bidding phases, specify '...
                           'how much effort you would be willing to spend to win the options shown.' ...
                           '\nThe duration of a bidding phase is approximately 5 seconds, but varies slightly. '...
                           'Try to keep the ball at the level you want to bid.'];

% experimental phase

if settings.do_fmri == 0
instr.strt_actual_train  = ['Now you will practice the actual task:' ...
                           '\nThe line will no longer move with the ball. '...
                           '\n\nTry applying pressure to move the ball up and over a red line. '...
                           'You can win points for every full second the ball stays above the red line. '...
                           'You can see that if the ball changes color to light blue you will win something.'];                       
elseif settings.do_fmri == 1
instr.strt_actual_train  = ['Now you will practice the actual task: '...
                            '\nThe line will no longer move with the ball. '...
                            '\n\nTry applying pressure to move the ball up and over a red line. '...
                            'You can will points for every full second the ball stays above the red line. '...
                            'You can see that if the ball changes color to light blue you will win something.'...
                            '\n\nThe following practice phase will take about 5 minutes.'];
end

if settings.do_fmri == 0
    instr.intro_exp1      = ['We will now start with the game that you practiced before. '...
                           'As a reminder, this is a simple game in which you play for money and a snack.' ...
                           '\n\nTry applzing pressure to move the ball up and over a red line. '...
                           'You can win points for every full second the ball stays above the red line. '...
                           'You can see that if the ball changes color to light blue you will win something.'];                       

elseif settings.do_fmri == 1
    instr.intro_exp1      = ['We will now start with the game that you practiced before. '...
                           'As a reminder, this is a simple game in which you play for money and a snack.' ...
                           '\n\nTry applzing pressure to move the ball up and over a red line. '...
                           'You can win points for every full second the ball stays above the red line.'];
end

%earlier instr.intro_uncer
instr.intro_uncer         = ['The difference to the practice earlier is that in some rounds you will not know exactly where the line is. '...
                           'In the half of the rounds you see a red area instead. '...
                           'The line that the ball has to cross to win points is somewhere inside this area. '...
                           'If you move the ball completely over this area, you will definitely collect food or money points. '...
                           'The ball does not change color in these rounds. '...
                           '\n\n However, as before, after the round you will see how many points you have collected. '...
                           'Then the actual position of the line will also be shown to you.'];                         
        
instr.intro_tvns         = ['The difference to practice earlier is that we stimulated the vagus nerve at the ear during the task.'...
                            'Each round will be accompanied by the stimulation of the vagus nerve from the experimenter.'];
% rewards        

instr.reward_nr1         = ['You can win different amounts in each round. '...
                           'You will be playing for money as well as for calories,' ...
                           'which you can exchange for a snack after completing the task. '...
                           'The current reward remains constant over a 24-second period' ...
                           'and is shown to you with the help of images.'];                        
         
instr.reward_nr2         = ['In some rounds you can win money points. '...
                           'After the task you will receive the corresponding amount of money. '...
                           '\n\nThe following conditions exist:'];                         

instr.reward_nr3         = ['In some runs you can win calories. '...
                           'After completing the task, you will receive the corresponding equivalent as a snack. '...
                           '\n\nThe following conditions exist: '];                         
    
                       
% difficulty
                      
instr.diff_nr1           = ['There will be different levels of difficulty over the course of the experiment. '...
                           'So it will not always be possible' ...
                           'to keep the ball completely above the line all the time. '...
                           'One way to deal with this' ...
                           'is to also take breaks during the rounds' ...
                           'in order to be able to apply more pressure afterwards.'];                        

instr.diff_exp           =  ['Reminder: During the experiment there will be different levels of difficulty. '...
                            'So it will not always be possible' ...
                            'to keep the ball completely above the line all the time. '...
                            'One way to deal with this' ...
                            'is to also take breaks during the rounds' ...
                            'in order to be able to apply more pressure afterwards.'];
                        
% VAS Instructions
                      
instr.vas_nr1          = ['After each round you will be shown a series of three questions:' ...
                          '\n\n How much did you exert yourself in this round? '...
                          '\n How much did you want to receive the reward in this round? '...
                          '\n How happy are you feeling at the moment? '...
                          '\n\n To answer, you can move the controller on a scale (not at all - very). '...
                          'Please use the mouse with your dominant hand. '...
                          'You must then confirm your answer by mouse click. '...
                          '\nPlease note that you only have a limited time for the answers. '...
                          'Do not think too long, but instead respond spontaneously. '...
                          'There is no right or wrong answer.'];                        
                        
                        
% Wheel of fortune related instructions // these don't exist in the German version      

instr.wof_train          = ['Next we will practice another game with a wheel of fortune,' ...
                            '\n in which you can win or lose money. '...
                            '\n During the main part of the experiment, the other task' ...
                            'that you just practiced will sometimes be interrupted by this wheel of fortune game. '...
                            '\n At the end, all winnings and losses from the game will be added together. '...
                            '\n However, the result of this practice round will not count. '];

instr.wof_exp            = ['From time to time the main game will be interrupted by the wheel of fortune game,' ...
                             'in which you can win or lose money. '...
                             '\n All you have to do for this part is click to start it.'];                        

instr.wof_panas          = ['At the beginning and at four further timepoints we will ask questions about how you feel. '...
                            '\n Just like the questions after each round, you only have a limited amount of time here. '...
                            '\n Do not think too long, but instead respond spontaneously. '...
                            'There is no right or wrong answer.'];
                        
                        
                        
% length/ask questions  
instr.time_train       = ['The following practice phase will take about 5 minutes. '...
                            'Please notify the experimenter. They will start the experiment for you.'];
     
if settings.do_fmri == 0                   
    instr.time_exp     = ['The entire experiment will take about 40 minutes. '...
                          '\nPlease notify the experimenter. They will start the experiment for you.'];
elseif settings.do_fmri == 1
    instr.time_exp     = ['The entire experiment will take about 30 minutes.'...
                          'If you have any questions, you can ask them at any time.'...
                          'When you feel ready, we can start the experiment.'];
end

% break // also no in the German version
                        
instr.break_exp          = ['You have completed a(nother) quarter of the experiment. '...
                            'You can take another break and rest.'];
                           
  
end

%% Electrogastrogram
if settings.do_EGG == 1
    
    % LPT port address
    settings.EGG.port_address = 888;
    % set trigger values for events
    settings.EGG.trigger.exp_on = 10;
    settings.EGG.trigger.cue_money = 50;
    settings.EGG.trigger.cue_food = 100;
    settings.EGG.trigger.cue_end = 120;
    settings.EGG.trigger.work_block = 150;
    settings.EGG.trigger.win = 160;
    settings.EGG.trigger.rest = 170;
    settings.EGG.trigger.work_block_end = 180;
    settings.EGG.trigger.feedback_certain = 200;
    settings.EGG.trigger.feedback_uncertain = 250;
    settings.EGG.trigger.feedback_end = 280;
    settings.EGG.trigger.exp_off = 255;
    
end


%% Save
name_file = strcat('EATsettings_', subj.study, '_S', subj.sessionNR, '_R', subj.runID, '.mat');
save(name_file)