%% Instructions tVNS German

% general

instr.text_coins1     = '1 Geld-Punkt pro Sekunde';
instr.text_coins10    = '10 Geld-Punkte pro Sekunde';
instr.text_cookies1   = '1 Essens-Punkt pro Sekunde';
instr.text_cookies10  = '10 Essens-Punkte pro Sekunde';

instr.text_Cont       = 'Weiter mit Mausklick.';

% training section
instr.train_welcome_text = ['Willkommen.' ...
                            '\n\nDies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen' ...
                            '\nSie koennen sich zunaechst mit den Funktionen vertraut machen und ein bisschen ueben.' ...
                            ' Das eigentliche Spiel wird dann zu einem späteren Zeitpunkt starten.'];
                  
instr.train_instr        = ['Auf dem Bildschirm werden Sie gleich ein nach oben geoeffnetes Gefaess sehen mit einem blauen Ball darin.' ...
                            ' Wenn Sie die rechte Taste am Controller mit Ihrem Zeigefinger druecken, bewegt sich der Ball nach oben.' ...
                            ' Je schneller Sie druecken, desto hoeher steigt der Ball.' ...
                            '\nSie haben jetzt zweimal 10 Sekunden Zeit, um den Ball so hoch wie moeglich steigen zu lassen.' ...
                            '\nDie hoechste erreichte Position wird mit einer blauen Linie angezeigt.'];
                  
instr.first_round_train  = ['Bitte veraendern Sie waehrend des Versuchs Ihre Handhaltung nicht.' ...
                            '\n\nVersuchen Sie in den naechsten 10 Sekunden den Ball so hoch steigen zu lassen, wie Sie koennen.'];
                  
instr.last_round_train   = 'Das war schon sehr gut. Versuchen Sie jetzt, den Ball noch hoeher steigen zu lassen.';

% bidding section
           
instr.bidding            = ['Die folgenden Durchgaengen dienen dazu, die Aufgabe fuer Sie individuell anzupassen.' ...
                            '\nIn mehreren Durchgaengen sehen Sie auf dem Bildschirm unterschiedliche Optionen, ' ...
                            'die Sie in diesem Spiel gewinnen koennen. \n\nDie Euromuenzen zeigen Geldbetraege an, '...
                            'die Schokoriegel zeigen Snacks an. Geben Sie in den darauffolgenden Gebots-Phasen an, ' ...
                            'wie viel Anstrengung Sie bereit waeren auszugeben, um die angezeigten Optionen zu gewinnen.' ...
                            '\nDie Dauer einer Gebots-Phase betraegt ungefaehr 5 Sekunden, variiert aber leicht. ' ...
                            'Versuchen Sie den Ball auf der Hoehe zu halten, die Sie zu “bieten” beabsichtigen.'];  
% experimental phase intro

instr.strt_actual_train  = ['Jetzt ueben Sie die eigentliche Aufgabe:' ...
                            '\nDie Linie wird sich nun nicht mehr mit dem Ball bewegen.' ...
                            '\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                            ' Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                            ' Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];
                        
instr.intro_exp1         = ['Wir beginnen nun mit dem Spiel, das Sie vorhin geuebt haben.' ... 
                            ' Zur Erinnerung: dies ist ein einfaches Spiel, bei dem Sie um Geld und einen Snack spielen.' ...
                            '\n\nVersuchen Sie mithilfe des Tastendrucks den Ball nach oben und ueber eine rote Linie zu bewegen.' ... 
                            ' Sie koennen Punkte gewinnen fuer jede volle Sekunde, die der Ball ueber der roten Linie bleibt.' ... 
                            ' Sie koennen erkennen, dass Sie etwas gewinnen, wenn der Ball seine Farbe zu hellblau aendert.'];

instr.intro_exp2         = ['Der Unterschied zur Uebung vorhin ist, dass Sie nicht in jedem Durchgang wissen werden, wo die Linie genau liegt.' ... 
                            ' In der Haelfte der Durchgaenge sehen Sie stattdessen einen roten Bereich.' ...
                            ' Die Linie, die der Ball uebersteigen muss um Punkte zu gewinnen, liegt irgendwo in diesem Bereich.'...
                            ' Wenn Sie den Ball also komplett ueber diesen Bereich bewegen, sammeln Sie auf jeden Fall Essens- oder Geld-Punkte.'...
                            ' In diesen Durchgaengen aendert der Ball seine Farbe nicht.' ...
                            '\n\n Wie zuvor sehen Sie jedoch nach dem Durchgang, wie viele Punkte Sie gesammelt haben. '...
                            ' Dann wird Ihnen auch die tatsaechliche Position der Linie angezeigt.'];
                      
% rewards

instr.reward_nr1         = ['Sie koennen in den einzelnen Durchgaengen unterschiedliche Gewinne erhalten.' ...
                            ' Sie spielen dabei sowohl fuer Geld als auch fuer Kalorien, '...
                            ' die Sie im Anschluss an die Aufgabe fuer einen Snack eintauschen koennen.'... 
                            ' Was die aktuelle Belohnung ist bleibt fuer einen Durchgang von 30 Sekunden konstant' ... 
                            ' und wird Ihnen mit Hilfe von Bildern angezeigt.'];
                        
instr.reward_nr2         = ['In manchen Durchgaengen koennen Sie Geld-Punkte gewinnen.'... 
                            ' Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Geldbetrag ausgezahlt.'...
                            '\n\nFolgende Bedingungen gibt es:'];
                        
instr.reward_nr3         = ['In manchen Durchgaengen koennen Sie Kalorien gewinnen.'...
                            ' Im Anschluss an die Aufgabe bekommen Sie den entsprechenden Gegenwert als Snack ausgegeben.'...
                            '\n\nFolgende Bedingungen gibt es:'];

instr.diff_nr1           = ['Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            ' Es wird also nicht immer moeglich sein, den Ball die ganze Zeit vollstaendig ueber der Linie zu halten.'...
                            ' Eine Moeglichkeit damit umzugehen, ist, auch waehrend eines Durchgangs Pausen zu machen'...
                            ' um danach wieder schneller druecken zu koennen.'];
                        
instr.diff_exp           =  ['Zur Erinnerung: Im Verlaufe des Experiments wird es unterschiedliche Schwierigkeitsstufen geben.'...
                            ' Es wird also nicht immer moeglich sein,' ...
                            ' den Ball die ganze Zeit vollstaendig ueber der Linie zu halten. ' ...
                            'Eine Moeglichkeit damit umzugehen ist,' ...
                            ' auch waehrend eines Durchgangs Pausen zu machen,' ...
                            ' um danach wieder staerkeren Druck ausueben zu koennen.']; 
                        
instr.vas_nr1            = ['Nach jedem Durchgang werden Ihnen nacheinander zwei Fragen angezeigt:'...
                            '\n\n' char(39) 'Wie stark haben Sie sich in diesem Durchgang verausgabt?' char(39) ' \n ' char(39) ...
                            ' Wie sehr wollten Sie die Belohnung in diesem Durchgang erhalten?' char(39) ...
                            '\n\nSie koennen zum Antworten den Regler auf einer Skala (ueberhaupt nicht - sehr) verschieben. '...
                            ' Nutzen Sie dazu bitte den linken Joystick auf dem Controller.'...
                            ' Ihre Antwort müssen Sie dann mit der gruenen A-Taste auf dem Controller bestaetigen.'...
                            '\nBitte beachten Sie, dass Sie fuer die Antworten nur eine begrenzte Zeit zur Verfuegung haben. '...
                            ' Ueberlegen Sie deshalb nicht zu lange, sondern antworten Sie spontan. '...
                            ' Es gibt dabei kein ' char(39) 'Richtig' char(39) ' oder ' char(39) 'Falsch' char(39) '.'];  
                        
instr.time_train         = ['Die nun folgende Uebungsphase wird ca. 5 Minuten dauern.\nSollten Sie noch Fragen haben, '...
                            ' koennen Sie diese jetzt stellen.\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.'];
                        
instr.time_exp           = ['Das gesamte Experiment wird ca. 40 Minuten dauern.\nSollten Sie noch Fragen haben,'...
                            ' koennen Sie diese jetzt stellen.\nWenn Sie sich bereit fuehlen, koennen wir jetzt mit dem Experiment beginnen.']; 
                                
                                
                                